/**
 * Frontend-facing API contract helpers (B32).
 *
 * Import wire types from `./contract` — keep UI view-models in `lib/types.ts`
 * separate and map at the client boundary.
 */
export { API_BASE } from './contract'
export type {
  APIError,
  Application,
  ApplicationConfigInput,
  ApplicationType,
  AuthResult,
  ConfigScope,
  CreateApplicationRequest,
  CreateDeploymentRequest,
  CreateProjectRequest,
  CreateServerRequest,
  DatabaseStatus,
  Deployment,
  DeploymentStatus,
  DeploymentTrigger,
  DNSStatus,
  EnvironmentKind,
  ErrorCode,
  ErrorEnvelope,
  HealthStatus,
  JSONObject,
  LoginRequest,
  LogoutRequest,
  Organization,
  Page,
  PageParams,
  Permission,
  PermissionKey,
  RefreshRequest,
  RegisterRequest,
  ReplicaStatus,
  RestartPolicy,
  RevisionStatus,
  RollbackRequest,
  ScaleReplicasRequest,
  Server,
  ServerStatus,
  SourceType,
  SystemRole,
  Timestamp,
  TLSStatus,
  TokenPair,
  User,
  UserStatus,
  UUID,
  VolumeState,
} from './contract'
