/**
 * Frontend-facing API contract helpers (B32).
 *
 * Import wire types from `./contract` — keep UI view-models in `lib/types.ts`
 * separate and map at the client boundary.
 */
export { API_BASE } from './contract'
export { apiClient, ApiError, tokenStorage, orgStorage } from './client'
export type {
  APIError,
  Application,
  ApplicationConfigInput,
  ApplicationType,
  AuthResult,
  ConfigScope,
  CreateApplicationRequest,
  CreateDeploymentRequest,
  CreateEnvironmentRequest,
  CreateProjectRequest,
  CreateServerRequest,
  Database,
  DatabaseStatus,
  Deployment,
  DeploymentStatus,
  DeploymentTrigger,
  Domain,
  CreateDomainRequest,
  UpdateDomainRequest,
  DNSStatus,
  Environment as WireEnvironment,
  EnvironmentKind,
  ErrorCode,
  ErrorEnvelope,
  HealthStatus,
  JSONObject,
  LoginRequest,
  LogoutRequest,
  Organization,
  Page,
  PageParams,
  Permission,
  PermissionKey,
  Project as WireProject,
  RefreshRequest,
  RegisterRequest,
  ReplicaStatus,
  RestartPolicy,
  RevisionStatus,
  RollbackRequest,
  ScaleReplicasRequest,
  Server,
  ServerStatus,
  SourceType,
  SystemRole,
  Timestamp,
  TLSStatus,
  TokenPair,
  UpdateEnvironmentRequest,
  UpdateProjectRequest,
  User,
  UserStatus,
  UUID,
  VolumeState,
} from './contract'
