package audit

// KnownActions documents high-value audited mutations (B27 completeness checklist).
// Not exhaustive of every writeAudit call site — used for docs/tests.
var KnownActions = []string{
	"auth.register",
	"auth.login.success",
	"auth.login.failure",
	"auth.login.denied",
	"auth.logout",
	"auth.password_reset.request",
	"auth.password_reset.complete",
	"organization.create",
	"organization.update",
	"organization.invite",
	"organization.invitation.accept",
	"organization.member.update_roles",
	"organization.member.remove",
	"server.create",
	"server.update",
	"server.disable",
	"server.enable",
	"server.delete",
	"server.maintenance.enter",
	"server.maintenance.exit",
	"server.agent.register",
	"server.agent.registration_token.issue",
	"secret.create",
	"secret.rotate",
	"secret.delete",
	"deployment.create",
	"deployment.rollback",
	"deployment.cancel",
	"domain.create",
	"domain.update",
	"domain.delete",
	"backup.create",
	"backup.delete",
	"backup.restore",
}
