package docker

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// --------------------------------------------------------------------------
// Validation patterns
// --------------------------------------------------------------------------

// containerNameRE allows DNS-label-safe names (alphanumeric and hyphens, no leading/trailing hyphen).
var containerNameRE = regexp.MustCompile(`^[a-z0-9]([a-z0-9\-]{0,61}[a-z0-9])?$`)

// slugRE validates Traefik service names and middleware names.
var slugRE = regexp.MustCompile(`^[a-z0-9][a-z0-9\-]{0,62}$`)

// hostRE is a permissive hostname / FQDN check.
var hostRE = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9\-\.]{0,251}[a-zA-Z0-9])?$`)

// imageRefRE validates an OCI image reference: [registry/]name[:tag|@digest]
// This is permissive but blocks obvious injection (whitespace, shell metas).
var imageRefRE = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9\-\./\:\_\@]{0,255}$`)

// envKeyRE validates environment variable names.
var envKeyRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// volumeNameRE allows alphanumeric, underscores, hyphens, and dots (Docker volume name standard).
var volumeNameRE = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_\-\.]{0,63}$`)

// networkNameRE allows alphanumeric, underscores, hyphens, and dots (Docker network name standard).
var networkNameRE = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_\-\.]{0,127}$`)

// --------------------------------------------------------------------------
// Label security policy
// --------------------------------------------------------------------------

// deniedLabelPrefixes lists label prefixes that are never allowed from callers.
// Traefik labels are safe because they are generated by trusted code, not caller-supplied.
var deniedLabelPrefixes = []string{
	"io.kubernetes.",
	"com.docker.swarm.",
	"com.docker.stack.",
	"com.docker.compose.",
	"org.opencontainers.image.", // must be controlled by build pipeline, not container create
	"deploycore.",               // callers cannot spoof platform tenancy or ownership labels
	"traefik.",                  // callers cannot inject arbitrary proxy routing rules
}

// --------------------------------------------------------------------------
// Docker socket detection
// --------------------------------------------------------------------------

// dockerSocketPaths is the set of Docker socket paths that are always blocked.
var dockerSocketPaths = []string{
	"/var/run/docker.sock",
	"/run/docker.sock",
}

// --------------------------------------------------------------------------
// Capability lists
// --------------------------------------------------------------------------

// hardDropCaps is the default set of capabilities always dropped for security.
// Source: Docker's default drop set + additional hardening.
var hardDropCaps = []string{
	"ALL", // drop all, then add back only what's needed
}

// allowedAddCaps is the curated set of capabilities that may be added via PrivilegedPolicy.
// This list is intentionally restrictive.
var allowedAddCaps = map[string]bool{
	"NET_BIND_SERVICE": true, // allow binding ports < 1024
	"CHOWN":            true,
	"SETUID":           true,
	"SETGID":           true,
	"DAC_OVERRIDE":     true,
}

// --------------------------------------------------------------------------
// Validation entry point
// --------------------------------------------------------------------------

// ValidationError aggregates one or more field-level validation errors.
type ValidationError struct {
	Fields []string
}

func (e *ValidationError) Error() string {
	return "container validation failed: " + strings.Join(e.Fields, "; ")
}

// validateCreateRequest checks a CreateContainerRequest for security and
// correctness violations. It returns a ValidationError listing all problems
// found, or nil if the request is valid.
func validateCreateRequest(req *CreateContainerRequest) error {
	var errs []string
	add := func(msg string) { errs = append(errs, msg) }

	// --- Name ---
	if req.Name != "" && !containerNameRE.MatchString(req.Name) {
		add("name: must be lowercase alphanumeric with optional hyphens, 1-63 chars")
	}

	// --- Image ---
	if req.Image == "" {
		add("image: required")
	} else if !imageRefRE.MatchString(req.Image) {
		add("image: invalid reference format")
	}

	// --- Environment variables ---
	for i, e := range req.Env {
		parts := strings.SplitN(e, "=", 2)
		if len(parts) < 2 {
			add(fmt.Sprintf("env[%d]: must be KEY=VALUE format", i))
			continue
		}
		if !envKeyRE.MatchString(parts[0]) {
			add(fmt.Sprintf("env[%d]: invalid key %q (must match [A-Za-z_][A-Za-z0-9_]*)", i, parts[0]))
		}
	}

	// --- Ports ---
	for i, p := range req.InternalPorts {
		if p.ContainerPort == 0 {
			add(fmt.Sprintf("port[%d]: containerPort is required and must be > 0", i))
		}
		if p.Protocol != "" && p.Protocol != "tcp" && p.Protocol != "udp" {
			add(fmt.Sprintf("port[%d]: protocol must be 'tcp' or 'udp'", i))
		}
		if p.HostPort > 0 && p.HostPort < 1024 {
			add(fmt.Sprintf("port[%d]: hostPort %d is a privileged port (<1024); use NET_BIND_SERVICE capability instead", i, p.HostPort))
		}
	}

	// --- Resource limits ---
	if req.CPUMillis < 0 {
		add("cpuMillis: must be >= 0")
	}
	if req.CPUMillis > 128_000 {
		add("cpuMillis: exceeds maximum allowed (128000 = 128 vCPU)")
	}
	if req.MemoryBytes < 0 {
		add("memoryBytes: must be >= 0")
	}
	// Minimum enforced memory: 4 MiB (Docker minimum)
	if req.MemoryBytes > 0 && req.MemoryBytes < 4*1024*1024 {
		add("memoryBytes: minimum is 4 MiB (4194304 bytes)")
	}

	// --- Restart policy ---
	switch req.RestartPolicy {
	case "", RestartNo, RestartAlways, RestartOnFailure, RestartUnlessStopped:
		// valid
	default:
		add(fmt.Sprintf("restartPolicy: unknown value %q", req.RestartPolicy))
	}

	// --- Volume mounts ---
	for i, v := range req.Volumes {
		if v.VolumeName == "" {
			add(fmt.Sprintf("volume[%d]: volumeName is required", i))
		} else if !strings.HasPrefix(v.VolumeName, "/") && !volumeNameRE.MatchString(v.VolumeName) {
			add(fmt.Sprintf("volume[%d]: invalid volume name format %q", i, v.VolumeName))
		}
		if v.MountPath == "" {
			add(fmt.Sprintf("volume[%d]: mountPath is required", i))
		} else if !strings.HasPrefix(v.MountPath, "/") {
			add(fmt.Sprintf("volume[%d]: mountPath must be an absolute path", i))
		}
	}

	// --- Networks ---
	for i, n := range req.Networks {
		if n == "" {
			add(fmt.Sprintf("network[%d]: empty network name/ID", i))
		} else if !networkNameRE.MatchString(n) {
			add(fmt.Sprintf("network[%d]: invalid network name/ID format %q", i, n))
		}
		if strings.EqualFold(n, "host") {
			if req.Policy == nil || !req.Policy.AllowHostNetwork {
				add("network: host network is blocked by default security policy")
			}
		}
	}

	// --- Caller-supplied labels ---
	for k := range req.Labels {
		for _, prefix := range deniedLabelPrefixes {
			if strings.HasPrefix(k, prefix) {
				add(fmt.Sprintf("label %q: prefix %q is not allowed", k, prefix))
			}
		}
	}

	// --- Traefik config ---
	if req.Traefik != nil && req.Traefik.Enabled {
		if err := validateTraefikConfig(req.Traefik); err != nil {
			add("traefik: " + err.Error())
		}
	}

	// --- Health check ---
	if req.HealthCheck != nil {
		if len(req.HealthCheck.Test) == 0 {
			add("healthCheck.test: at least one element required")
		}
	}

	// --- Security policy ---
	if err := validateSecurityPolicy(req); err != nil {
		var ve *ValidationError
		if errors.As(err, &ve) {
			errs = append(errs, ve.Fields...)
		} else {
			add(err.Error())
		}
	}

	if len(errs) > 0 {
		return &ValidationError{Fields: errs}
	}
	return nil
}

// validateSecurityPolicy checks that any dangerous options are explicitly permitted
// via PrivilegedPolicy and that the policy itself is coherent.
func validateSecurityPolicy(req *CreateContainerRequest) error {
	var errs []string
	add := func(msg string) { errs = append(errs, msg) }

	policy := req.Policy

	// Policy is always checked — a nil policy = all dangerous features blocked.

	// Docker socket detection & raw host paths
	for _, v := range req.Volumes {
		isDockerSocket := false
		for _, sock := range dockerSocketPaths {
			if v.VolumeName == sock {
				isDockerSocket = true
				break
			}
		}
		if (isDockerSocket && (policy == nil || !policy.AllowDockerSocket)) ||
			(strings.HasPrefix(v.VolumeName, "/") && (policy == nil || !policy.AllowArbitraryHostPaths)) {
			add(fmt.Sprintf("volume %q: Docker socket / raw host path mounts are blocked by security policy", v.VolumeName))
		}
	}

	if policy == nil {
		// All dangerous options are implicitly blocked; nothing further to check.
		if len(errs) > 0 {
			return &ValidationError{Fields: errs}
		}
		return nil
	}

	// Explicit privileged-policy hooks for future admin-authorized workloads (disabled by default)
	if policy.AllowPrivileged {
		add("privileged mode requires explicit admin grant (reserved for future use)")
	}
	if policy.AllowHostPID {
		add("host PID namespace requires explicit admin grant (reserved for future use)")
	}
	if policy.AllowHostIPC {
		add("host IPC namespace requires explicit admin grant (reserved for future use)")
	}
	if policy.AllowHostNetwork {
		add("host network requires explicit admin grant (reserved for future use)")
	}
	if policy.AllowDockerSocket {
		add("Docker socket mount requires explicit admin grant (reserved for future use)")
	}
	if policy.AllowArbitraryHostPaths {
		add("raw host path mounts require explicit admin grant (reserved for future use)")
	}
	if policy.AllowDevicePassthrough {
		add("device passthrough requires explicit admin grant (reserved for future use)")
	}

	// Capability allowlist check
	for _, cap := range policy.AddCapabilities {
		if !allowedAddCaps[cap] {
			add(fmt.Sprintf("capability %q is not in the permitted add-capability list", cap))
		}
	}

	if len(errs) > 0 {
		return &ValidationError{Fields: errs}
	}
	return nil
}

// validateTraefikConfig validates the typed Traefik input.
func validateTraefikConfig(tc *TraefikConfig) error {
	var errs []string

	if len(tc.Domains) > 0 {
		for i, d := range tc.Domains {
			if d.Hostname == "" {
				errs = append(errs, fmt.Sprintf("domains[%d].hostname is required", i))
			} else if !hostRE.MatchString(d.Hostname) {
				errs = append(errs, fmt.Sprintf("domains[%d].hostname %q is not a valid hostname", i, d.Hostname))
			}
			if d.PathPrefix != "" && !strings.HasPrefix(d.PathPrefix, "/") {
				errs = append(errs, fmt.Sprintf("domains[%d].pathPrefix must start with /", i))
			}
			for j, mw := range d.Middlewares {
				if !slugRE.MatchString(mw) {
					errs = append(errs, fmt.Sprintf("domains[%d].middleware[%d] %q must be a lowercase slug", i, j, mw))
				}
			}
		}
	} else {
		if tc.Host == "" {
			errs = append(errs, "host is required")
		} else if !hostRE.MatchString(tc.Host) {
			errs = append(errs, fmt.Sprintf("host %q is not a valid hostname", tc.Host))
		}
		if tc.PathPrefix != "" && !strings.HasPrefix(tc.PathPrefix, "/") {
			errs = append(errs, "pathPrefix must start with /")
		}
	}

	if tc.Port == 0 {
		errs = append(errs, "port is required")
	}
	if tc.ServiceName == "" {
		errs = append(errs, "serviceName is required")
	} else if !slugRE.MatchString(tc.ServiceName) {
		errs = append(errs, fmt.Sprintf("serviceName %q must be a lowercase slug", tc.ServiceName))
	}
	for i, mw := range tc.Middlewares {
		if !slugRE.MatchString(mw) {
			errs = append(errs, fmt.Sprintf("middleware[%d] %q must be a lowercase slug", i, mw))
		}
	}
	if len(errs) > 0 {
		return errors.New(strings.Join(errs, "; "))
	}
	return nil
}

// effectiveDropCaps returns the capabilities that should be dropped.
// If the policy specifies custom drops, those are used; otherwise the
// hardened defaults are returned.
func effectiveDropCaps(policy *PrivilegedPolicy) []string {
	if policy != nil && len(policy.DropCapabilities) > 0 {
		return policy.DropCapabilities
	}
	return hardDropCaps
}
