package docker

import (
	"io"
	"time"
)

// ErrCode represents a stable agent-level Docker error code.
type ErrCode string

const (
	ErrCodeNotFound          ErrCode = "DOCKER_NOT_FOUND"
	ErrCodeConflict          ErrCode = "DOCKER_CONFLICT"
	ErrCodePermission        ErrCode = "DOCKER_PERMISSION_DENIED"
	ErrCodeTimeout           ErrCode = "DOCKER_TIMEOUT"
	ErrCodeDaemonUnavailable ErrCode = "DOCKER_DAEMON_UNAVAILABLE"
	ErrCodeImagePullFailed   ErrCode = "DOCKER_IMAGE_PULL_FAILED"
	ErrCodeUnknown           ErrCode = "DOCKER_UNKNOWN_ERROR"
)

// AgentError is a stable error type that abstracts raw Docker daemon errors.
type AgentError struct {
	Code    ErrCode
	Message string
}

func (e *AgentError) Error() string {
	return string(e.Code) + ": " + e.Message
}

// ContainerSummary is a sanitized summary of a Docker container.
type ContainerSummary struct {
	ID      string
	Names   []string
	Image   string
	ImageID string
	Command string
	State   string
	Status  string
	Created time.Time
	Labels  map[string]string
	Ports   []PortBinding
}

// PortBinding represents a published port.
type PortBinding struct {
	IP          string
	PrivatePort uint16
	PublicPort  uint16
	Type        string
}

// ContainerDetail is the full inspected detail for a container.
type ContainerDetail struct {
	ID           string
	Name         string
	Image        string
	ImageID      string
	State        ContainerState
	Created      time.Time
	StartedAt    *time.Time
	FinishedAt   *time.Time
	RestartCount int
	Labels       map[string]string
	Env          []string
	Mounts       []MountPoint
	NetworkMode  string
	IPAddress    string
	Networks     map[string]string // network name -> IP address
}

// ContainerHealth holds the container's health status if a HEALTHCHECK is configured.
type ContainerHealth struct {
	Status        string // "none", "starting", "healthy", "unhealthy"
	FailingStreak int
}

// ContainerState holds the runtime state of a container.
type ContainerState struct {
	Status     string
	Running    bool
	Paused     bool
	Restarting bool
	Dead       bool
	Pid        int
	ExitCode   int
	Error      string
	Health     *ContainerHealth
}

// ExecResult contains output and exit code from an in-container exec operation.
type ExecResult struct {
	ExitCode int
	Stdout   string
	Stderr   string
}

// MountPoint describes a container mount.
type MountPoint struct {
	Type        string
	Source      string
	Destination string
	Mode        string
	RW          bool
}

// RestartPolicy controls container restart behaviour.
type RestartPolicy string

const (
	RestartNo            RestartPolicy = "no"
	RestartAlways        RestartPolicy = "always"
	RestartOnFailure     RestartPolicy = "on-failure"
	RestartUnlessStopped RestartPolicy = "unless-stopped"
)

// PortMapping maps a container-internal port to an optional host port.
// HostPort = "" means Docker picks an ephemeral port.
type PortMapping struct {
	ContainerPort uint16 `json:"containerPort"`      // required
	Protocol      string `json:"protocol,omitempty"` // "tcp" (default) or "udp"
	HostPort      uint16 `json:"hostPort,omitempty"` // 0 = ephemeral
	HostIP        string `json:"hostIp,omitempty"`   // "" = 0.0.0.0
}

// VolumeMount attaches a platform-managed volume to a container path.
// Raw host paths are not permitted here; they must go through the policy layer.
type VolumeMount struct {
	VolumeName string // name of a Docker volume managed by DeployCore
	MountPath  string // absolute path inside the container
	ReadOnly   bool
}

// HealthCheckConfig maps to Docker's HEALTHCHECK instruction.
type HealthCheckConfig struct {
	Test        []string      // CMD or CMD-SHELL slice
	Interval    time.Duration // 0 = Docker default (30s)
	Timeout     time.Duration // 0 = Docker default (30s)
	StartPeriod time.Duration
	Retries     int
}

// DomainConfig defines routing and TLS policy for an individual domain.
type DomainConfig struct {
	Hostname          string   `json:"hostname"`
	IsPrimary         bool     `json:"isPrimary"`
	ForceHTTPS        bool     `json:"forceHTTPS"`
	PathPrefix        string   `json:"pathPrefix,omitempty"`
	Middlewares       []string `json:"middlewares,omitempty"`
	RedirectToPrimary bool     `json:"redirectToPrimary,omitempty"`
	CertResolver      string   `json:"certResolver,omitempty"`
}

// TraefikConfig is the typed input for Traefik reverse-proxy label generation.
// Labels are generated by trusted code from these fields — callers cannot inject
// arbitrary label values.
type TraefikConfig struct {
	Enabled         bool           `json:"enabled"`
	ServiceName     string         `json:"serviceName"`    // used as the Traefik router/service name; must be slug-safe
	Port            uint16         `json:"port"`           // container port Traefik should route to
	Host            string         `json:"host,omitempty"` // legacy single-host support
	TLS             bool           `json:"tls,omitempty"`  // legacy single-host TLS flag
	PathPrefix      string         `json:"pathPrefix,omitempty"`
	Middlewares     []string       `json:"middlewares,omitempty"`
	Domains         []DomainConfig `json:"domains,omitempty"` // multi-domain routing
	EnableWebSocket bool           `json:"enableWebSocket,omitempty"`
	TraefikNetwork  string         `json:"traefikNetwork,omitempty"` // explicitly controlled network (default: deploycore-proxy)
}

// PrivilegedPolicy controls dangerous host capabilities.
// All fields default to false (blocked). Enabling any field requires an
// explicit privileged-policy grant — reserved for future admin-authorised workflows.
type PrivilegedPolicy struct {
	// AllowPrivileged enables Docker --privileged mode.
	AllowPrivileged bool
	// AllowHostPID enables --pid=host.
	AllowHostPID bool
	// AllowHostIPC enables --ipc=host.
	AllowHostIPC bool
	// AllowHostNetwork enables --network=host.
	AllowHostNetwork bool
	// AllowDockerSocket permits mounting /var/run/docker.sock.
	AllowDockerSocket bool
	// AllowArbitraryHostPaths permits any host path bind mount.
	AllowArbitraryHostPaths bool
	// AllowDevicePassthrough permits --device flags.
	AllowDevicePassthrough bool
	// AddCapabilities lists Linux capabilities to add. Empty by default.
	// Only a curated allow-list is accepted when the policy is enabled.
	AddCapabilities []string
	// DropCapabilities are always applied; defaults to the full hardened drop set.
	DropCapabilities []string
}

// CreateContainerRequest is the full, validated input for container creation.
// All dangerous Docker primitives are blocked by default and must be explicitly
// allowed via PrivilegedPolicy (which itself must be nil / default to enforce
// the security baseline).
type CreateContainerRequest struct {
	// Name is the platform container name. Must be DNS-label safe.
	Name string
	// Image is the OCI image reference. Must be a non-empty, valid reference.
	Image string
	// Entrypoint overrides the image entrypoint. Optional.
	Entrypoint []string
	// Command overrides the image CMD. Optional.
	Command []string
	// Env holds KEY=VALUE environment entries. Values are treated as opaque secrets;
	// they are never logged or emitted in results.
	Env []string
	// InternalPorts declares the container ports to expose.
	// No host port binding is generated from this field alone.
	InternalPorts []PortMapping
	// CPUMillis is the CPU allocation in milli-cores (e.g. 500 = 0.5 CPU).
	// 0 = unlimited.
	CPUMillis int64
	// MemoryBytes is the hard memory limit in bytes. 0 = unlimited.
	MemoryBytes int64
	// RestartPolicy controls automatic restart behaviour.
	RestartPolicy RestartPolicy
	// Networks is a list of Docker network names/IDs to connect the container to.
	Networks []string
	// Volumes lists managed volume mounts. Host paths are blocked unless
	// PrivilegedPolicy.AllowArbitraryHostPaths is true.
	Volumes []VolumeMount
	// Traefik generates Traefik reverse-proxy labels from typed config.
	// nil = no Traefik labels.
	Traefik *TraefikConfig
	// HealthCheck configures the container health check. nil = no HEALTHCHECK.
	HealthCheck *HealthCheckConfig
	// ReadOnlyRootFS makes the container root filesystem read-only.
	ReadOnlyRootFS bool
	// Labels are additional user-supplied non-Traefik labels.
	// Platform-reserved labels (e.g. "deploycore.*") are blocked to prevent spoofing.
	Labels map[string]string
	// PlatformLabels contains trusted platform labels generated by DeployCore internal logic
	// (e.g. deploycore.managed, deploycore.organization_id). Callers cannot supply these.
	PlatformLabels map[string]string
	// Policy grants specific privileged capabilities.
	// nil = all dangerous options blocked (the safe default).
	Policy *PrivilegedPolicy
}

// CreateContainerResult contains the created container's ID and warnings.
type CreateContainerResult struct {
	ID       string
	Warnings []string
}

// ImageSummary is a sanitized image list entry.
type ImageSummary struct {
	ID          string
	ParentID    string
	RepoTags    []string
	RepoDigests []string
	Created     time.Time
	Size        int64
	Labels      map[string]string
}

// ImageDetail is the inspected detail of an image.
type ImageDetail struct {
	ID           string
	RepoTags     []string
	RepoDigests  []string
	Parent       string
	Created      time.Time
	Size         int64
	Architecture string
	OS           string
}

// RegistryAuth contains credentials for authenticated image registries.
// In-memory credentials must be scrubbed after use to avoid persisting secrets.
type RegistryAuth struct {
	Username      string `json:"username,omitempty"`
	Password      string `json:"password,omitempty"`
	ServerAddress string `json:"serverAddress,omitempty"`
	IdentityToken string `json:"identityToken,omitempty"`
	RegistryToken string `json:"registryToken,omitempty"`
}

// Zero clears sensitive fields from memory.
func (a *RegistryAuth) Zero() {
	if a == nil {
		return
	}
	a.Password = ""
	a.IdentityToken = ""
	a.RegistryToken = ""
}

// PullProgressEvent represents a structured progress event from Docker image pull.
type PullProgressEvent struct {
	ID        string    `json:"id,omitempty"`
	Status    string    `json:"status"`
	Progress  string    `json:"progress,omitempty"`
	Current   int64     `json:"current,omitempty"`
	Total     int64     `json:"total,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

// PullProgressFunc is a callback invoked as progress events arrive.
type PullProgressFunc func(event PullProgressEvent)

// PullImageOptions configures an image pull operation.
type PullImageOptions struct {
	Ref          string
	RegistryAuth *RegistryAuth
	ProgressFn   PullProgressFunc
}

// PullImageResult represents the structured result of an image pull operation.
type PullImageResult struct {
	Digest         string        `json:"digest"`
	ImageID        string        `json:"imageId"`
	Size           int64         `json:"size"`
	PullDuration   time.Duration `json:"pullDuration"`
	PullDurationMs int64         `json:"pullDurationMs"`
	Status         string        `json:"status"`
}

// BuildImageOptions configures a Docker image build operation.
type BuildImageOptions struct {
	Context    io.Reader
	Dockerfile string
	Tags       []string
	BuildArgs  map[string]*string
	Target     string
	Platform   string
	NoCache    bool
	PullParent bool
	ProgressFn BuildProgressFunc
	Timeout    time.Duration
}

// BuildProgressEvent represents a build progress or log event.
type BuildProgressEvent struct {
	Stream    string    `json:"stream,omitempty"`
	AuxID     string    `json:"auxId,omitempty"`
	Error     string    `json:"error,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

// BuildProgressFunc is a callback invoked as build progress events arrive.
type BuildProgressFunc func(event BuildProgressEvent)

// BuildImageResult contains metadata from a completed image build.
type BuildImageResult struct {
	ImageID         string        `json:"imageId"`
	Digest          string        `json:"digest,omitempty"`
	Size            int64         `json:"size"`
	BuildDuration   time.Duration `json:"buildDuration"`
	BuildDurationMs int64         `json:"buildDurationMs"`
	Tags            []string      `json:"tags"`
	Status          string        `json:"status"`
}

// NetworkSummary is a sanitized network list entry.
type NetworkSummary struct {
	ID     string
	Name   string
	Driver string
	Scope  string
	Labels map[string]string
}

// CreateNetworkRequest is the sanitized input for creating a network.
type CreateNetworkRequest struct {
	Name     string
	Driver   string
	Internal bool
	Labels   map[string]string
	Options  map[string]string
}

// NetworkEndpoint represents a container connected to a network.
type NetworkEndpoint struct {
	Name        string `json:"name"`
	EndpointID  string `json:"endpointId"`
	MacAddress  string `json:"macAddress"`
	IPv4Address string `json:"ipv4Address"`
	IPv6Address string `json:"ipv6Address"`
}

// NetworkDetail contains full inspected network information.
type NetworkDetail struct {
	ID         string                     `json:"id"`
	Name       string                     `json:"name"`
	Driver     string                     `json:"driver"`
	Scope      string                     `json:"scope"`
	Internal   bool                       `json:"internal"`
	Attachable bool                       `json:"attachable"`
	Labels     map[string]string          `json:"labels"`
	Containers map[string]NetworkEndpoint `json:"containers"`
	Options    map[string]string          `json:"options"`
}

// VolumeSummary is a sanitized volume list entry.
type VolumeSummary struct {
	Name       string
	Driver     string
	Mountpoint string
	Labels     map[string]string
	Scope      string
}

// VolumeUsage contains disk and reference usage metadata for a volume.
type VolumeUsage struct {
	SizeBytes int64 `json:"sizeBytes"`
	RefCount  int64 `json:"refCount"`
}

// VolumeDetail contains full inspected volume information.
type VolumeDetail struct {
	Name       string            `json:"name"`
	Driver     string            `json:"driver"`
	Mountpoint string            `json:"mountpoint"`
	CreatedAt  string            `json:"createdAt"`
	Labels     map[string]string `json:"labels"`
	Scope      string            `json:"scope"`
	Options    map[string]string `json:"options"`
	Status     map[string]any    `json:"status,omitempty"`
	Usage      *VolumeUsage      `json:"usage,omitempty"`
}

// CreateVolumeRequest is the sanitized input for creating a volume.
type CreateVolumeRequest struct {
	Name       string
	Driver     string
	DriverOpts map[string]string
	Labels     map[string]string
}

// LogOptions configures log streaming.
type LogOptions struct {
	Follow     bool
	Since      string
	Until      string
	Tail       string // "all" or a number
	Timestamps bool
}

// ContainerStatsSnapshot is a sanitized point-in-time container resource snapshot.
type ContainerStatsSnapshot struct {
	ID          string
	CPUPercent  float64
	MemoryUsage int64
	MemoryLimit int64
	NetworkRx   int64
	NetworkTx   int64
	BlockRead   int64
	BlockWrite  int64
	PidsCurrent int64
}

// Event is a sanitized Docker daemon event.
type Event struct {
	Type    string
	Action  string
	ActorID string
	Time    time.Time
	Scope   string
	Attrs   map[string]string
}

// PingResult holds the Docker daemon ping response.
type PingResult struct {
	APIVersion     string
	OSType         string
	Experimental   bool
	BuilderVersion string
}

// InfoResult holds daemon info.
type InfoResult struct {
	ServerVersion string
	OS            string
	Architecture  string
	CPUs          int
	MemoryBytes   int64
}

// VersionResult holds daemon version info.
type VersionResult struct {
	Version       string
	APIVersion    string
	GoVersion     string
	GitCommit     string
	OS            string
	Architecture  string
	KernelVersion string
}
