import type {
  ActivityItem,
  Application,
  AuditLogEntry,
  BackupJob,
  BackupRun,
  Container,
  ContainerImage,
  DatabaseInstance,
  Deployment,
  DockerNetwork,
  DomainRecord,
  EnvVarEntry,
  FeatureFlag,
  GitProviderConnection,
  HealthCheckConfig,
  LogLine,
  NotificationChannel,
  NotificationPolicy,
  Organization,
  PermissionLevel,
  PlatformJob,
  Project,
  Registry,
  Revision,
  SecretItem,
  Server,
  Team,
  Invitation,
  TeamMember,
  Volume,
  Webhook,
} from './types'
import {
  buildDeploymentEvents,
  buildDeploymentSteps,
  currentPhaseForStatus,
} from './deployments'

export const servers: Server[] = [
  {
    id: 'srv-01',
    name: 'oci-singapore-01',
    provider: 'Oracle Cloud',
    region: 'ap-southeast-1',
    ip: '158.101.44.12',
    privateIp: '10.0.1.4',
    cpu: 62,
    cpuCores: 8,
    memory: 71,
    memoryTotalGb: 32,
    disk: 48,
    diskTotalGb: 500,
    containers: 14,
    agentVersion: 'v2.4.1',
    status: 'running',
    lastHeartbeatAt: new Date(Date.now() - 5000).toISOString(),
    lastHeartbeat: '4s ago',
    os: 'Ubuntu 22.04.4 LTS',
    arch: 'x86_64',
    dockerVersion: '25.0.3',
    uptime: '41d 6h',
    load: [1.2, 1.4, 1.1],
  },
  {
    id: 'srv-02',
    name: 'hetzner-fsn1-02',
    provider: 'Hetzner',
    region: 'eu-central-1',
    ip: '95.216.11.203',
    privateIp: '10.0.2.7',
    cpu: 38,
    cpuCores: 4,
    memory: 55,
    memoryTotalGb: 16,
    disk: 71,
    diskTotalGb: 250,
    containers: 9,
    agentVersion: 'v2.4.1',
    status: 'running',
    lastHeartbeatAt: new Date(Date.now() - 5000).toISOString(),
    lastHeartbeat: '2s ago',
    os: 'Ubuntu 22.04.4 LTS',
    arch: 'x86_64',
    dockerVersion: '25.0.3',
    uptime: '112d 2h',
    load: [0.8, 0.9, 0.7],
  },
  {
    id: 'srv-03',
    name: 'aws-us-east-04',
    provider: 'AWS',
    region: 'us-east-1',
    ip: '54.221.90.5',
    privateIp: '10.0.3.9',
    cpu: 91,
    cpuCores: 16,
    memory: 88,
    memoryTotalGb: 64,
    disk: 63,
    diskTotalGb: 1000,
    containers: 27,
    agentVersion: 'v2.4.0',
    status: 'degraded',
    lastHeartbeatAt: new Date(Date.now() - 5000).toISOString(),
    lastHeartbeat: '11s ago',
    os: 'Ubuntu 22.04.3 LTS',
    arch: 'x86_64',
    dockerVersion: '24.0.9',
    uptime: '8d 19h',
    load: [12.4, 10.1, 9.8],
  },
  {
    id: 'srv-04',
    name: 'hetzner-hel1-01',
    provider: 'Hetzner',
    region: 'eu-north-1',
    ip: '95.217.4.88',
    privateIp: '10.0.4.2',
    cpu: 21,
    cpuCores: 4,
    memory: 34,
    memoryTotalGb: 16,
    disk: 29,
    diskTotalGb: 250,
    containers: 5,
    agentVersion: 'v2.4.1',
    status: 'running',
    lastHeartbeatAt: new Date(Date.now() - 5000).toISOString(),
    lastHeartbeat: '6s ago',
    os: 'Ubuntu 22.04.4 LTS',
    arch: 'x86_64',
    dockerVersion: '25.0.3',
    uptime: '203d 11h',
    load: [0.4, 0.5, 0.3],
  },
  {
    id: 'srv-05',
    name: 'oci-frankfurt-02',
    provider: 'Oracle Cloud',
    region: 'eu-frankfurt-1',
    ip: '138.2.77.19',
    privateIp: '10.0.5.6',
    cpu: 0,
    cpuCores: 8,
    memory: 0,
    memoryTotalGb: 32,
    disk: 12,
    diskTotalGb: 500,
    containers: 0,
    agentVersion: 'v2.3.8',
    status: 'offline',
    lastHeartbeatAt: new Date(Date.now() - 5000).toISOString(),
    lastHeartbeat: '19m ago',
    os: 'Ubuntu 22.04.3 LTS',
    arch: 'x86_64',
    dockerVersion: '24.0.9',
    uptime: '0m',
    load: [0, 0, 0],
  },
  {
    id: 'srv-06',
    name: 'bare-metal-dc3',
    provider: 'Self-hosted',
    region: 'on-prem',
    ip: '192.168.1.14',
    privateIp: '192.168.1.14',
    cpu: 15,
    cpuCores: 32,
    memory: 22,
    memoryTotalGb: 128,
    disk: 8,
    diskTotalGb: 4000,
    containers: 3,
    agentVersion: 'v2.4.1',
    status: 'maintenance',
    lastHeartbeatAt: new Date(Date.now() - 5000).toISOString(),
    lastHeartbeat: '1s ago',
    os: 'Debian 12',
    arch: 'x86_64',
    dockerVersion: '25.0.3',
    uptime: '340d 4h',
    load: [2.1, 2.0, 1.9],
  },
]

export const projects: Project[] = [
  {
    id: 'proj-01',
    name: 'Daya Platform',
    slug: 'daya-platform',
    environments: ['Production', 'Staging', 'Preview'],
    applicationCount: 6,
    health: 'healthy',
    lastDeployment: '12 min ago',
    owner: { name: 'Amara Osei' },
    updatedAt: '12 min ago',
  },
  {
    id: 'proj-02',
    name: 'Ledger Core',
    slug: 'ledger-core',
    environments: ['Production', 'Staging'],
    applicationCount: 4,
    health: 'degraded',
    lastDeployment: '2 hr ago',
    owner: { name: 'Marcus Lindqvist' },
    updatedAt: '38 min ago',
  },
  {
    id: 'proj-03',
    name: 'Signal Ingest',
    slug: 'signal-ingest',
    environments: ['Production'],
    applicationCount: 3,
    health: 'healthy',
    lastDeployment: '1 day ago',
    owner: { name: 'Priya Chandran' },
    updatedAt: '3 hr ago',
  },
  {
    id: 'proj-04',
    name: 'Internal Tools',
    slug: 'internal-tools',
    environments: ['Production', 'Staging'],
    applicationCount: 5,
    health: 'healthy',
    lastDeployment: '5 hr ago',
    owner: { name: 'Jonas Weber' },
    updatedAt: '5 hr ago',
  },
  {
    id: 'proj-05',
    name: 'Edge Gateway',
    slug: 'edge-gateway',
    environments: ['Production', 'Staging', 'Preview'],
    applicationCount: 2,
    health: 'failed',
    lastDeployment: '19 min ago',
    owner: { name: 'Amara Osei' },
    updatedAt: '19 min ago',
  },
]

export const applications: Application[] = [
  {
    id: 'app-daya-api',
    name: 'daya-api',
    projectId: 'proj-01',
    project: 'Daya Platform',
    environment: 'Production',
    runtime: 'API',
    server: 'oci-singapore-01',
    revision: '00049',
    status: 'healthy',
    domain: 'api.daya.io',
    lastDeployment: '12 min ago',
    repo: 'daya/daya-api',
    branch: 'main',
    commit: '8f3a2c1',
    commitMessage: 'fix: correct pagination cursor overflow',
    cpu: 34,
    cpuLimit: 2,
    memory: 61,
    memoryLimit: 2048,
    instances: 3,
    uptime: '12d 4h',
  },
  {
    id: 'app-daya-web',
    name: 'daya-web',
    projectId: 'proj-01',
    project: 'Daya Platform',
    environment: 'Production',
    runtime: 'Web Service',
    server: 'hetzner-fsn1-02',
    revision: '00112',
    status: 'healthy',
    domain: 'app.daya.io',
    lastDeployment: '38 min ago',
    repo: 'daya/daya-web',
    branch: 'main',
    commit: 'a91cd44',
    commitMessage: 'feat: add usage chart to billing page',
    cpu: 22,
    cpuLimit: 1,
    memory: 44,
    memoryLimit: 1024,
    instances: 2,
    uptime: '2d 1h',
  },
  {
    id: 'app-daya-worker',
    name: 'daya-worker',
    projectId: 'proj-01',
    project: 'Daya Platform',
    environment: 'Production',
    runtime: 'Worker',
    server: 'oci-singapore-01',
    revision: '00031',
    status: 'deploying',
    domain: '—',
    lastDeployment: 'deploying now',
    repo: 'daya/daya-worker',
    branch: 'main',
    commit: 'c7e10bb',
    commitMessage: 'chore: bump queue concurrency to 12',
    cpu: 58,
    cpuLimit: 1,
    memory: 39,
    memoryLimit: 1024,
    instances: 1,
    uptime: '0m',
  },
  {
    id: 'app-ledger-api',
    name: 'ledger-api',
    projectId: 'proj-02',
    project: 'Ledger Core',
    environment: 'Production',
    runtime: 'API',
    server: 'aws-us-east-04',
    revision: '00204',
    status: 'degraded',
    domain: 'ledger.internal.io',
    lastDeployment: '2 hr ago',
    repo: 'ledger/ledger-api',
    branch: 'main',
    commit: '4dd88e2',
    commitMessage: 'perf: cache account balance lookups',
    cpu: 88,
    cpuLimit: 4,
    memory: 92,
    memoryLimit: 4096,
    instances: 4,
    uptime: '8d 19h',
  },
  {
    id: 'app-ledger-recon',
    name: 'ledger-reconciler',
    projectId: 'proj-02',
    project: 'Ledger Core',
    environment: 'Production',
    runtime: 'Scheduled Job',
    server: 'aws-us-east-04',
    revision: '00058',
    status: 'healthy',
    domain: '—',
    lastDeployment: '6 hr ago',
    repo: 'ledger/ledger-reconciler',
    branch: 'main',
    commit: '11f0aa9',
    commitMessage: 'fix: handle currency rounding edge case',
    cpu: 12,
    cpuLimit: 1,
    memory: 28,
    memoryLimit: 512,
    instances: 1,
    uptime: '6h 2m',
  },
  {
    id: 'app-signal-collector',
    name: 'signal-collector',
    projectId: 'proj-03',
    project: 'Signal Ingest',
    environment: 'Production',
    runtime: 'Worker',
    server: 'hetzner-hel1-01',
    revision: '00087',
    status: 'healthy',
    domain: '—',
    lastDeployment: '1 day ago',
    repo: 'signal/collector',
    branch: 'main',
    commit: 'd502f13',
    commitMessage: 'feat: support gzip payloads',
    cpu: 19,
    cpuLimit: 1,
    memory: 31,
    memoryLimit: 512,
    instances: 2,
    uptime: '31d 8h',
  },
  {
    id: 'app-signal-docs',
    name: 'signal-docs',
    projectId: 'proj-03',
    project: 'Signal Ingest',
    environment: 'Production',
    runtime: 'Static Site',
    server: 'hetzner-hel1-01',
    revision: '00014',
    status: 'healthy',
    domain: 'docs.signal.io',
    lastDeployment: '4 day ago',
    repo: 'signal/docs',
    branch: 'main',
    commit: '99a1b0c',
    commitMessage: 'docs: update webhook reference',
    cpu: 3,
    cpuLimit: 1,
    memory: 8,
    memoryLimit: 256,
    instances: 1,
    uptime: '31d 8h',
  },
  {
    id: 'app-tools-admin',
    name: 'tools-admin',
    projectId: 'proj-04',
    project: 'Internal Tools',
    environment: 'Production',
    runtime: 'Web Service',
    server: 'bare-metal-dc3',
    revision: '00042',
    status: 'healthy',
    domain: 'admin.internal.io',
    lastDeployment: '5 hr ago',
    repo: 'platform/tools-admin',
    branch: 'main',
    commit: '2bb771e',
    commitMessage: 'feat: add impersonation audit trail',
    cpu: 9,
    cpuLimit: 1,
    memory: 21,
    memoryLimit: 512,
    instances: 1,
    uptime: '5h 1m',
  },
  {
    id: 'app-edge-router',
    name: 'edge-router',
    projectId: 'proj-05',
    project: 'Edge Gateway',
    environment: 'Production',
    runtime: 'Docker Image',
    server: 'oci-frankfurt-02',
    revision: '00019',
    status: 'failed',
    domain: 'edge.daya.io',
    lastDeployment: '19 min ago',
    repo: 'platform/edge-router',
    branch: 'main',
    commit: '77a0cde',
    commitMessage: 'fix: update TLS cert bundle',
    cpu: 0,
    cpuLimit: 1,
    memory: 0,
    memoryLimit: 512,
    instances: 0,
    uptime: '0m',
  },
  {
    id: 'app-edge-cache',
    name: 'edge-cache',
    projectId: 'proj-05',
    project: 'Edge Gateway',
    environment: 'Staging',
    runtime: 'Docker Compose',
    server: 'hetzner-fsn1-02',
    revision: '00007',
    status: 'pending',
    domain: 'edge-stg.daya.io',
    lastDeployment: 'queued',
    repo: 'platform/edge-cache',
    branch: 'staging',
    commit: 'f01aa22',
    commitMessage: 'test: add cache invalidation suite',
    cpu: 0,
    cpuLimit: 1,
    memory: 0,
    memoryLimit: 512,
    instances: 0,
    uptime: '0m',
  },
]

const enrichDeployment = (
  deployment: Omit<Deployment, 'phase' | 'steps' | 'events' | 'failureReason'> & {
    failureReason?: Deployment['failureReason']
  },
): Deployment => {
  const failureReason = deployment.failureReason
  return {
    ...deployment,
    phase: currentPhaseForStatus(deployment.status, failureReason),
    failureReason,
    steps: buildDeploymentSteps(deployment.status, failureReason),
    events: buildDeploymentEvents(deployment.status, deployment.application, failureReason),
  }
}

export const deployments: Deployment[] = [
  enrichDeployment({
    id: 'dep-293',
    number: 293,
    applicationId: 'app-daya-api',
    application: 'daya-api',
    project: 'Daya Platform',
    environment: 'Production',
    revision: '00049',
    commit: '8f3a2c1',
    commitMessage: 'fix: correct pagination cursor overflow',
    author: { name: 'Amara Osei' },
    triggeredBy: 'Amara Osei',
    status: 'healthy',
    duration: '1m 42s',
    startedAt: '12 min ago',
    repo: 'daya/daya-api',
    branch: 'main',
    server: 'oci-singapore-01',
    image: 'registry.deploycore.io/daya-api:8f3a2c1',
  }),
  enrichDeployment({
    id: 'dep-292',
    number: 292,
    applicationId: 'app-daya-worker',
    application: 'daya-worker',
    project: 'Daya Platform',
    environment: 'Production',
    revision: '00031',
    commit: 'c7e10bb',
    commitMessage: 'chore: bump queue concurrency to 12',
    author: { name: 'Jonas Weber' },
    triggeredBy: 'Jonas Weber',
    status: 'deploying',
    duration: '46s',
    startedAt: '46s ago',
    repo: 'daya/daya-worker',
    branch: 'main',
    server: 'oci-singapore-01',
    image: 'registry.deploycore.io/daya-worker:c7e10bb',
  }),
  enrichDeployment({
    id: 'dep-291',
    number: 291,
    applicationId: 'app-edge-router',
    application: 'edge-router',
    project: 'Edge Gateway',
    environment: 'Production',
    revision: '00019',
    commit: '77a0cde',
    commitMessage: 'fix: update TLS cert bundle',
    author: { name: 'Priya Chandran' },
    triggeredBy: 'Priya Chandran',
    status: 'failed',
    failureReason: 'BUILD_FAILED',
    duration: '38s',
    startedAt: '19 min ago',
    repo: 'platform/edge-router',
    branch: 'main',
    server: 'oci-frankfurt-02',
    image: 'registry.deploycore.io/edge-router:77a0cde',
  }),
  enrichDeployment({
    id: 'dep-290',
    number: 290,
    applicationId: 'app-edge-cache',
    application: 'edge-cache',
    project: 'Edge Gateway',
    environment: 'Staging',
    revision: '00007',
    commit: 'f01aa22',
    commitMessage: 'test: add cache invalidation suite',
    author: { name: 'Marcus Lindqvist' },
    triggeredBy: 'Marcus Lindqvist',
    status: 'queued',
    duration: '—',
    startedAt: 'queued 2 min ago',
    repo: 'platform/edge-cache',
    branch: 'staging',
    server: 'hetzner-fsn1-02',
    image: 'registry.deploycore.io/edge-cache:f01aa22',
  }),
  enrichDeployment({
    id: 'dep-289',
    number: 289,
    applicationId: 'app-daya-web',
    application: 'daya-web',
    project: 'Daya Platform',
    environment: 'Production',
    revision: '00112',
    commit: 'a91cd44',
    commitMessage: 'feat: add usage chart to billing page',
    author: { name: 'Amara Osei' },
    triggeredBy: 'Amara Osei',
    status: 'healthy',
    duration: '2m 05s',
    startedAt: '38 min ago',
    repo: 'daya/daya-web',
    branch: 'main',
    server: 'hetzner-fsn1-02',
    image: 'registry.deploycore.io/daya-web:a91cd44',
  }),
  enrichDeployment({
    id: 'dep-288',
    number: 288,
    applicationId: 'app-ledger-api',
    application: 'ledger-api',
    project: 'Ledger Core',
    environment: 'Production',
    revision: '00204',
    commit: '4dd88e2',
    commitMessage: 'perf: cache account balance lookups',
    author: { name: 'Marcus Lindqvist' },
    triggeredBy: 'Marcus Lindqvist',
    status: 'healthy',
    duration: '3m 18s',
    startedAt: '2 hr ago',
    repo: 'ledger/ledger-api',
    branch: 'main',
    server: 'aws-us-east-04',
    image: 'registry.deploycore.io/ledger-api:4dd88e2',
  }),
  enrichDeployment({
    id: 'dep-287',
    number: 287,
    applicationId: 'app-tools-admin',
    application: 'tools-admin',
    project: 'Internal Tools',
    environment: 'Production',
    revision: '00042',
    commit: '2bb771e',
    commitMessage: 'feat: add impersonation audit trail',
    author: { name: 'Jonas Weber' },
    triggeredBy: 'Jonas Weber',
    status: 'healthy',
    duration: '1m 09s',
    startedAt: '5 hr ago',
    repo: 'platform/tools-admin',
    branch: 'main',
    server: 'bare-metal-dc3',
    image: 'registry.deploycore.io/tools-admin:2bb771e',
  }),
  enrichDeployment({
    id: 'dep-286',
    number: 286,
    applicationId: 'app-signal-collector',
    application: 'signal-collector',
    project: 'Signal Ingest',
    environment: 'Production',
    revision: '00087',
    commit: 'd502f13',
    commitMessage: 'feat: support gzip payloads',
    author: { name: 'Priya Chandran' },
    triggeredBy: 'Priya Chandran',
    status: 'healthy',
    duration: '58s',
    startedAt: '1 day ago',
    repo: 'signal/collector',
    branch: 'main',
    server: 'hetzner-hel1-01',
    image: 'registry.deploycore.io/signal-collector:d502f13',
  }),
  enrichDeployment({
    id: 'dep-285',
    number: 285,
    applicationId: 'app-ledger-recon',
    application: 'ledger-reconciler',
    project: 'Ledger Core',
    environment: 'Staging',
    revision: '00088',
    commit: '9aa11c0',
    commitMessage: 'chore: cancel noisy staging rollout',
    author: { name: 'Marcus Lindqvist' },
    triggeredBy: 'Marcus Lindqvist',
    status: 'cancelled',
    failureReason: 'CANCELLED',
    duration: '12s',
    startedAt: '3 hr ago',
    repo: 'ledger/reconciler',
    branch: 'staging',
    server: 'aws-us-east-04',
    image: 'registry.deploycore.io/ledger-reconciler:9aa11c0',
  }),
  enrichDeployment({
    id: 'dep-284',
    number: 284,
    applicationId: 'app-daya-api',
    application: 'daya-api',
    project: 'Daya Platform',
    environment: 'Preview',
    revision: '00048',
    commit: '1a9e0dd',
    commitMessage: 'fix: health probe timeout under load',
    author: { name: 'Amara Osei' },
    triggeredBy: 'Amara Osei',
    status: 'failed',
    failureReason: 'HEALTH_CHECK_FAILED',
    duration: '2m 11s',
    startedAt: '6 hr ago',
    repo: 'daya/daya-api',
    branch: 'preview',
    server: 'hetzner-fsn1-02',
    image: 'registry.deploycore.io/daya-api:1a9e0dd',
  }),
]

export const databases: DatabaseInstance[] = [
  {
    id: 'db-01',
    name: 'daya-primary',
    type: 'PostgreSQL',
    version: '16.2',
    project: 'Daya Platform',
    environment: 'Production',
    server: 'oci-singapore-01',
    storageUsedGb: 84,
    storageTotalGb: 200,
    backups: 42,
    lastBackup: '38 min ago',
    status: 'healthy',
    dbName: 'daya',
    port: 5432,
    username: 'daya_app',
    connectionHost: 'daya-primary.internal',
    credentialsRevealAllowed: true,
  },
  {
    id: 'db-02',
    name: 'ledger-primary',
    type: 'PostgreSQL',
    version: '15.6',
    project: 'Ledger Core',
    environment: 'Production',
    server: 'aws-us-east-04',
    storageUsedGb: 311,
    storageTotalGb: 500,
    backups: 30,
    lastBackup: '2 hr ago',
    status: 'degraded',
    dbName: 'ledger',
    port: 5432,
    username: 'ledger_app',
    connectionHost: 'ledger-primary.internal',
    credentialsRevealAllowed: true,
  },
  {
    id: 'db-03',
    name: 'signal-timeseries',
    type: 'PostgreSQL',
    version: '16.2',
    project: 'Signal Ingest',
    environment: 'Production',
    server: 'hetzner-hel1-01',
    storageUsedGb: 152,
    storageTotalGb: 250,
    backups: 60,
    lastBackup: '12 min ago',
    status: 'healthy',
    dbName: 'signal',
    port: 5432,
    username: 'signal_writer',
    connectionHost: 'signal-timeseries.internal',
    credentialsRevealAllowed: false,
  },
  {
    id: 'db-04',
    name: 'session-cache',
    type: 'Redis',
    version: '7.2',
    project: 'Daya Platform',
    environment: 'Production',
    server: 'hetzner-fsn1-02',
    storageUsedGb: 3,
    storageTotalGb: 8,
    backups: 0,
    lastBackup: 'not configured',
    status: 'healthy',
    dbName: '0',
    port: 6379,
    username: 'default',
    connectionHost: 'session-cache.internal',
    credentialsRevealAllowed: true,
  },
  {
    id: 'db-05',
    name: 'tools-metadata',
    type: 'MySQL',
    version: '8.0',
    project: 'Internal Tools',
    environment: 'Production',
    server: 'bare-metal-dc3',
    storageUsedGb: 5,
    storageTotalGb: 50,
    backups: 14,
    lastBackup: '5 hr ago',
    status: 'healthy',
    dbName: 'tools',
    port: 3306,
    username: 'tools_app',
    connectionHost: 'tools-metadata.internal',
    credentialsRevealAllowed: true,
  },
]

export const activityFeed: ActivityItem[] = [
  { id: 'act-1', actor: 'Amara Osei', action: 'deployed', target: 'daya-api #293', timestamp: '12 min ago', tone: 'success' },
  { id: 'act-2', actor: 'Jonas Weber', action: 'started deployment for', target: 'daya-worker #292', timestamp: '46s ago', tone: 'info' },
  { id: 'act-3', actor: 'System', action: 'flagged certificate expiring for', target: 'edge.daya.io', timestamp: '18 min ago', tone: 'warning' },
  { id: 'act-4', actor: 'Priya Chandran', action: 'deployment failed for', target: 'edge-router #291', timestamp: '19 min ago', tone: 'critical' },
  { id: 'act-5', actor: 'Marcus Lindqvist', action: 'rotated secret', target: 'LEDGER_DB_PASSWORD', timestamp: '1 hr ago', tone: 'info' },
  { id: 'act-6', actor: 'System', action: 'completed backup for', target: 'daya-primary', timestamp: '38 min ago', tone: 'success' },
  { id: 'act-7', actor: 'Amara Osei', action: 'added server', target: 'bare-metal-dc3', timestamp: '3 hr ago', tone: 'info' },
]

export const incidents = [
  { id: 'inc-1', title: 'Elevated latency on ledger-api', severity: 'warning' as const, startedAt: '2 hr ago', status: 'Investigating' },
  { id: 'inc-2', title: 'edge-router deployment failure', severity: 'critical' as const, startedAt: '19 min ago', status: 'Identified' },
  { id: 'inc-3', title: 'aws-us-east-04 approaching CPU limit', severity: 'warning' as const, startedAt: '41 min ago', status: 'Monitoring' },
]

export const certificateWarnings = [
  { domain: 'edge.daya.io', expiresIn: '4 days', status: 'critical' as const },
  { domain: 'docs.signal.io', expiresIn: '22 days', status: 'warning' as const },
]

export const backupStatus = [
  { name: 'daya-primary', lastBackup: '38 min ago', status: 'success' as const },
  { name: 'ledger-primary', lastBackup: '2 hr ago', status: 'success' as const },
  { name: 'signal-timeseries', lastBackup: '12 min ago', status: 'success' as const },
  { name: 'tools-metadata', lastBackup: '5 hr ago', status: 'warning' as const },
]

export const auditLog: AuditLogEntry[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-14 09:41:02',
    actor: 'amara@daya.io',
    action: 'secret.update',
    resource: 'LEDGER_DB_PASSWORD',
    project: 'Ledger Core',
    ip: '203.0.113.4',
    result: 'success',
    before: { fingerprint: 'fp_7a91…', rotated: 'false' },
    after: { fingerprint: 'fp_c3e2…', rotated: 'true' },
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-14 09:22:47',
    actor: 'jonas@daya.io',
    action: 'deployment.trigger',
    resource: 'daya-worker',
    project: 'Daya Platform',
    ip: '203.0.113.9',
    result: 'success',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-14 09:18:11',
    actor: 'priya@daya.io',
    action: 'application.restart',
    resource: 'edge-router',
    project: 'Edge Gateway',
    ip: '203.0.113.21',
    result: 'failure',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-14 08:55:39',
    actor: 'marcus@daya.io',
    action: 'access.role_change',
    resource: 'user:sofia@daya.io',
    project: 'Ledger Core',
    ip: '203.0.113.14',
    result: 'success',
    before: { role: 'Viewer' },
    after: { role: 'Developer' },
  },
  {
    id: 'aud-5',
    timestamp: '2026-09-14 08:02:15',
    actor: 'system',
    action: 'server.agent_disconnected',
    resource: 'oci-frankfurt-02',
    project: 'Edge Gateway',
    ip: '138.2.77.19',
    result: 'failure',
  },
  {
    id: 'aud-6',
    timestamp: '2026-09-14 07:41:00',
    actor: 'amara@daya.io',
    action: 'server.add',
    resource: 'bare-metal-dc3',
    project: '—',
    ip: '203.0.113.4',
    result: 'success',
    after: { provider: 'Self-hosted', region: 'dc3' },
  },
  {
    id: 'aud-7',
    timestamp: '2026-09-14 06:18:44',
    actor: 'amara@daya.io',
    action: 'invitation.create',
    resource: 'lena@daya.io',
    project: 'Daya Platform',
    ip: '203.0.113.4',
    result: 'success',
    after: { role: 'Developer', team: 'Platform' },
  },
  {
    id: 'aud-8',
    timestamp: '2026-09-13 22:05:11',
    actor: 'priya@daya.io',
    action: 'env_var.update',
    resource: 'LOG_LEVEL',
    project: 'Daya Platform',
    ip: '203.0.113.21',
    result: 'success',
    before: { scope: 'Organization', value: 'info' },
    after: { scope: 'Environment', value: 'debug' },
  },
]

export const secrets: SecretItem[] = [
  {
    id: 'sec-1',
    name: 'DATABASE_URL',
    scope: 'Project',
    applications: ['daya-api', 'daya-worker'],
    updatedAt: '3 day ago',
    updatedBy: 'Amara Osei',
    lastRotatedAt: '3 day ago',
    accessRoles: ['Owner', 'Admin', 'Developer'],
    description: 'Primary Postgres connection string for Daya',
  },
  {
    id: 'sec-2',
    name: 'LEDGER_DB_PASSWORD',
    scope: 'Application',
    applications: ['ledger-api'],
    updatedAt: '1 hr ago',
    updatedBy: 'Marcus Lindqvist',
    lastRotatedAt: '1 hr ago',
    accessRoles: ['Owner', 'Admin'],
    description: 'Ledger database password',
  },
  {
    id: 'sec-3',
    name: 'STRIPE_SECRET_KEY',
    scope: 'Organization',
    applications: ['daya-api', 'daya-web'],
    updatedAt: '2 week ago',
    updatedBy: 'Amara Osei',
    lastRotatedAt: '2 week ago',
    accessRoles: ['Owner', 'Admin'],
    description: 'Stripe live API secret',
  },
  {
    id: 'sec-4',
    name: 'SIGNAL_INGEST_TOKEN',
    scope: 'Application',
    applications: ['signal-collector'],
    updatedAt: '5 day ago',
    updatedBy: 'Priya Chandran',
    lastRotatedAt: '5 day ago',
    accessRoles: ['Owner', 'Admin', 'Developer'],
  },
  {
    id: 'sec-5',
    name: 'SMTP_CREDENTIALS',
    scope: 'Organization',
    applications: ['tools-admin'],
    updatedAt: '1 month ago',
    updatedBy: 'Jonas Weber',
    lastRotatedAt: '1 month ago',
    accessRoles: ['Owner'],
    description: 'Transactional email credentials',
  },
]

export const revisions: Revision[] = [
  {
    id: 'rev-daya-api-00049',
    number: '00049',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    environment: 'Production',
    status: 'healthy',
    traffic: 100,
    commit: '8f3a2c1',
    commitMessage: 'fix: correct pagination cursor overflow',
    image: 'registry.deploycore.io/daya-api:8f3a2c1',
    imageDigest: 'sha256:9d2c4a1e7f0b3c88d6a51f2e9c0b7a44f3d1e8c9a0b6f4d2e1c8a7b6f5e4d3c2',
    createdBy: { name: 'Amara Osei' },
    createdAt: '12 min ago',
    runtime: 'API',
    server: 'oci-singapore-01',
    command: 'node dist/server.js --workers=4 --port=8080',
    cpuLimit: 2,
    memoryLimit: 2048,
    envVarCount: 5,
    envVars: [
      { key: 'NODE_ENV', scope: 'Environment', secret: false },
      { key: 'LOG_LEVEL', scope: 'Application', secret: false },
      { key: 'RATE_LIMIT_RPM', scope: 'Application', secret: false },
      { key: 'DATABASE_URL', scope: 'Project', secret: true },
      { key: 'STRIPE_SECRET_KEY', scope: 'Organization', secret: true },
    ],
    secretRefs: ['DATABASE_URL', 'STRIPE_SECRET_KEY'],
    domains: ['api.daya.io'],
    volumes: [],
    healthCheck: { type: 'HTTP', path: '/healthz', interval: '30s' },
  },
  {
    id: 'rev-daya-api-00048',
    number: '00048',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    environment: 'Production',
    status: 'stopped',
    traffic: 0,
    commit: '1a9e0dd',
    commitMessage: 'chore: bump dependencies',
    image: 'registry.deploycore.io/daya-api:1a9e0dd',
    imageDigest: 'sha256:7b1a3c9d5e2f0a44c8b6d1e9f7a2c5b3d0e8f1a9c6b4d2e0f8a7c5b3d1e9f2a4',
    createdBy: { name: 'Amara Osei' },
    createdAt: '1 day ago',
    runtime: 'API',
    server: 'oci-singapore-01',
    command: 'node dist/server.js --workers=4 --port=8080',
    cpuLimit: 2,
    memoryLimit: 2048,
    envVarCount: 5,
    envVars: [
      { key: 'NODE_ENV', scope: 'Environment', secret: false },
      { key: 'LOG_LEVEL', scope: 'Application', secret: false },
      { key: 'RATE_LIMIT_RPM', scope: 'Application', secret: false },
      { key: 'DATABASE_URL', scope: 'Project', secret: true },
      { key: 'STRIPE_SECRET_KEY', scope: 'Organization', secret: true },
    ],
    secretRefs: ['DATABASE_URL', 'STRIPE_SECRET_KEY'],
    domains: ['api.daya.io'],
    volumes: [],
    healthCheck: { type: 'HTTP', path: '/healthz', interval: '30s' },
  },
  {
    id: 'rev-daya-api-00047',
    number: '00047',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    environment: 'Production',
    status: 'stopped',
    traffic: 0,
    commit: 'e40c112',
    commitMessage: 'feat: add rate limit headers',
    image: 'registry.deploycore.io/daya-api:e40c112',
    imageDigest: 'sha256:2e8f1a9c6b4d2e0f8a7c5b3d1e9f2a47b1a3c9d5e2f0a44c8b6d1e9f7a2c5b3d',
    createdBy: { name: 'Jonas Weber' },
    createdAt: '3 day ago',
    runtime: 'API',
    server: 'oci-singapore-01',
    command: 'node dist/server.js --workers=2 --port=8080',
    cpuLimit: 1,
    memoryLimit: 1024,
    envVarCount: 4,
    envVars: [
      { key: 'NODE_ENV', scope: 'Environment', secret: false },
      { key: 'LOG_LEVEL', scope: 'Application', secret: false },
      { key: 'DATABASE_URL', scope: 'Project', secret: true },
      { key: 'STRIPE_SECRET_KEY', scope: 'Organization', secret: true },
    ],
    secretRefs: ['DATABASE_URL', 'STRIPE_SECRET_KEY'],
    domains: ['api.daya.io'],
    volumes: [],
    healthCheck: { type: 'HTTP', path: '/healthz', interval: '15s' },
  },
  {
    id: 'rev-daya-api-00040',
    number: '00040',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    environment: 'Production',
    status: 'stopped',
    traffic: 0,
    commit: '91bb0aa',
    commitMessage: 'chore: archive pre-rate-limit baseline',
    image: 'registry.deploycore.io/daya-api:91bb0aa',
    imageDigest: 'sha256:a0b1c2d3e4f5061728394a5b6c7d8e9f0a1b2c3d4e5f60718293a4b5c6d7e8f9',
    createdBy: { name: 'Amara Osei' },
    createdAt: '21 day ago',
    runtime: 'API',
    server: 'oci-singapore-01',
    command: 'node dist/server.js --workers=2 --port=8080',
    cpuLimit: 1,
    memoryLimit: 1024,
    envVarCount: 3,
    envVars: [
      { key: 'NODE_ENV', scope: 'Environment', secret: false },
      { key: 'DATABASE_URL', scope: 'Project', secret: true },
      { key: 'STRIPE_SECRET_KEY', scope: 'Organization', secret: true },
    ],
    secretRefs: ['DATABASE_URL', 'STRIPE_SECRET_KEY'],
    domains: ['api.daya.io'],
    volumes: [],
    healthCheck: { type: 'HTTP', path: '/healthz', interval: '15s' },
    archived: true,
  },
  {
    id: 'rev-daya-web-00112',
    number: '00112',
    applicationId: 'app-daya-web',
    application: 'daya-web',
    environment: 'Production',
    status: 'healthy',
    traffic: 80,
    commit: 'a91cd44',
    commitMessage: 'feat: add usage chart to billing page',
    image: 'registry.deploycore.io/daya-web:a91cd44',
    imageDigest: 'sha256:c6b4d2e0f8a7c5b3d1e9f2a49d2c4a1e7f0b3c88d6a51f2e9c0b7a44f3d1e8c9',
    createdBy: { name: 'Amara Osei' },
    createdAt: '38 min ago',
    runtime: 'Web Service',
    server: 'hetzner-fsn1-02',
    command: 'next start --port 3000',
    cpuLimit: 1,
    memoryLimit: 1024,
    envVarCount: 3,
    envVars: [
      { key: 'NODE_ENV', scope: 'Environment', secret: false },
      { key: 'NEXT_PUBLIC_API_URL', scope: 'Application', secret: false },
      { key: 'STRIPE_SECRET_KEY', scope: 'Organization', secret: true },
    ],
    secretRefs: ['STRIPE_SECRET_KEY'],
    domains: ['app.daya.io'],
    volumes: [],
    healthCheck: { type: 'HTTP', path: '/', interval: '30s' },
  },
  {
    id: 'rev-daya-web-00111',
    number: '00111',
    applicationId: 'app-daya-web',
    application: 'daya-web',
    environment: 'Production',
    status: 'healthy',
    traffic: 20,
    commit: '5cc9a02',
    commitMessage: 'fix: sidebar collapse state on mobile',
    image: 'registry.deploycore.io/daya-web:5cc9a02',
    imageDigest: 'sha256:f8a7c5b3d1e9f2a4c6b4d2e0b1a3c9d5e2f0a44c8b6d1e9f7a2c5b3d1e9f2a4c',
    createdBy: { name: 'Priya Chandran' },
    createdAt: '6 hr ago',
    runtime: 'Web Service',
    server: 'hetzner-fsn1-02',
    command: 'next start --port 3000',
    cpuLimit: 1,
    memoryLimit: 1024,
    envVarCount: 3,
    envVars: [
      { key: 'NODE_ENV', scope: 'Environment', secret: false },
      { key: 'NEXT_PUBLIC_API_URL', scope: 'Application', secret: false },
      { key: 'STRIPE_SECRET_KEY', scope: 'Organization', secret: true },
    ],
    secretRefs: ['STRIPE_SECRET_KEY'],
    domains: ['app.daya.io'],
    volumes: [],
    healthCheck: { type: 'HTTP', path: '/', interval: '30s' },
  },
  {
    id: 'rev-ledger-api-00204',
    number: '00204',
    applicationId: 'app-ledger-api',
    application: 'ledger-api',
    environment: 'Production',
    status: 'degraded',
    traffic: 100,
    commit: '4dd88e2',
    commitMessage: 'perf: cache account balance lookups',
    image: 'registry.deploycore.io/ledger-api:4dd88e2',
    imageDigest: 'sha256:1e9f2a4c6b4d2e0f8a7c5b3d9d2c4a1e7f0b3c88d6a51f2e9c0b7a44f3d1e8c9',
    createdBy: { name: 'Marcus Lindqvist' },
    createdAt: '2 hr ago',
    runtime: 'API',
    server: 'aws-us-east-04',
    command: 'java -jar /app/ledger.jar --spring.profiles.active=prod',
    cpuLimit: 4,
    memoryLimit: 4096,
    envVarCount: 4,
    envVars: [
      { key: 'SPRING_PROFILES_ACTIVE', scope: 'Environment', secret: false },
      { key: 'LEDGER_CACHE_TTL', scope: 'Application', secret: false },
      { key: 'LEDGER_DB_PASSWORD', scope: 'Application', secret: true },
      { key: 'JAVA_OPTS', scope: 'Application', secret: false },
    ],
    secretRefs: ['LEDGER_DB_PASSWORD'],
    domains: ['ledger.internal.io'],
    volumes: ['ledger-audit-store'],
    healthCheck: { type: 'HTTP', path: '/health', interval: '15s' },
  },
  {
    id: 'rev-ledger-api-00201',
    number: '00201',
    applicationId: 'app-ledger-api',
    application: 'ledger-api',
    environment: 'Production',
    status: 'stopped',
    traffic: 0,
    commit: '0cfe991',
    commitMessage: 'fix: reconnect pool after failover',
    image: 'registry.deploycore.io/ledger-api:0cfe991',
    imageDigest: 'sha256:55aa11bb22cc33dd44ee55ff6677889900aabbccddeeff001122334455667788',
    createdBy: { name: 'Marcus Lindqvist' },
    createdAt: '4 day ago',
    runtime: 'API',
    server: 'aws-us-east-04',
    command: 'java -jar /app/ledger.jar --spring.profiles.active=prod',
    cpuLimit: 4,
    memoryLimit: 4096,
    envVarCount: 3,
    envVars: [
      { key: 'SPRING_PROFILES_ACTIVE', scope: 'Environment', secret: false },
      { key: 'LEDGER_DB_PASSWORD', scope: 'Application', secret: true },
      { key: 'JAVA_OPTS', scope: 'Application', secret: false },
    ],
    secretRefs: ['LEDGER_DB_PASSWORD'],
    domains: ['ledger.internal.io'],
    volumes: ['ledger-audit-store'],
    healthCheck: { type: 'HTTP', path: '/health', interval: '15s' },
  },
]

export const domains: DomainRecord[] = [
  {
    id: 'dom-01',
    domain: 'api.daya.io',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    environment: 'Production',
    routingPort: 8080,
    dnsVerified: true,
    https: true,
    certExpiry: '2026-11-02',
    certExpiryDays: 49,
    status: 'healthy',
    tlsState: 'ACTIVE',
    certificateIssuer: "Let's Encrypt",
    certificateIssuedAt: '2026-08-04',
    nextRenewalAt: '2026-10-19',
    lastValidatedAt: '2 min ago',
    validationMessage: 'DNS and certificate checks passed',
    primary: true,
    forceHttps: true,
    requiredRecord: { type: 'CNAME', name: 'api', value: 'edge.deploycore.io' },
    detectedRecord: { type: 'CNAME', name: 'api', value: 'edge.deploycore.io' },
    redirectRules: [],
  },
  {
    id: 'dom-02',
    domain: 'app.daya.io',
    applicationId: 'app-daya-web',
    application: 'daya-web',
    environment: 'Production',
    routingPort: 3000,
    dnsVerified: true,
    https: true,
    certExpiry: '2026-10-18',
    certExpiryDays: 34,
    status: 'healthy',
    tlsState: 'ACTIVE',
    certificateIssuer: "Let's Encrypt",
    certificateIssuedAt: '2026-07-20',
    nextRenewalAt: '2026-10-04',
    lastValidatedAt: '8 min ago',
    validationMessage: 'DNS and certificate checks passed',
    primary: true,
    forceHttps: true,
    requiredRecord: { type: 'CNAME', name: 'app', value: 'edge.deploycore.io' },
    detectedRecord: { type: 'CNAME', name: 'app', value: 'edge.deploycore.io' },
    redirectRules: [{ from: 'www.daya.io', to: 'app.daya.io', code: 301 }],
  },
  {
    id: 'dom-03',
    domain: 'docs.signal.io',
    applicationId: 'app-signal-docs',
    application: 'signal-docs',
    environment: 'Production',
    routingPort: 80,
    dnsVerified: true,
    https: true,
    certExpiry: '2026-10-06',
    certExpiryDays: 22,
    status: 'degraded',
    tlsState: 'EXPIRING',
    certificateIssuer: "Let's Encrypt",
    certificateIssuedAt: '2026-07-08',
    nextRenewalAt: '2026-09-22',
    lastValidatedAt: '14 min ago',
    validationMessage: 'Certificate renews within 30 days — renewal queued',
    primary: true,
    forceHttps: true,
    requiredRecord: { type: 'CNAME', name: 'docs', value: 'edge.deploycore.io' },
    detectedRecord: { type: 'CNAME', name: 'docs', value: 'edge.deploycore.io' },
    redirectRules: [],
  },
  {
    id: 'dom-04',
    domain: 'admin.internal.io',
    applicationId: 'app-tools-admin',
    application: 'tools-admin',
    environment: 'Production',
    routingPort: 4000,
    dnsVerified: true,
    https: true,
    certExpiry: '2027-01-14',
    certExpiryDays: 122,
    status: 'healthy',
    tlsState: 'ACTIVE',
    certificateIssuer: 'Internal CA',
    certificateIssuedAt: '2026-01-14',
    nextRenewalAt: '2026-12-15',
    lastValidatedAt: '1 min ago',
    validationMessage: 'DNS and certificate checks passed',
    primary: true,
    forceHttps: false,
    requiredRecord: { type: 'A', name: 'admin', value: '192.168.1.14' },
    detectedRecord: { type: 'A', name: 'admin', value: '192.168.1.14' },
    redirectRules: [],
  },
  {
    id: 'dom-05',
    domain: 'edge.daya.io',
    applicationId: 'app-edge-router',
    application: 'edge-router',
    environment: 'Production',
    routingPort: 443,
    dnsVerified: true,
    https: true,
    certExpiry: '2026-09-18',
    certExpiryDays: 4,
    status: 'failed',
    tlsState: 'FAILED',
    certificateIssuer: "Let's Encrypt",
    certificateIssuedAt: '2026-06-20',
    nextRenewalAt: null,
    lastValidatedAt: '19 min ago',
    validationMessage: 'Certificate renewal failed — ACME challenge timed out',
    primary: true,
    forceHttps: true,
    requiredRecord: { type: 'CNAME', name: 'edge', value: 'edge.deploycore.io' },
    detectedRecord: { type: 'CNAME', name: 'edge', value: 'edge.deploycore.io' },
    redirectRules: [],
  },
  {
    id: 'dom-06',
    domain: 'edge-stg.daya.io',
    applicationId: 'app-edge-cache',
    application: 'edge-cache',
    environment: 'Staging',
    routingPort: 8081,
    dnsVerified: false,
    https: false,
    certExpiry: '—',
    certExpiryDays: 0,
    status: 'pending',
    tlsState: 'PENDING',
    certificateIssuer: null,
    certificateIssuedAt: null,
    nextRenewalAt: null,
    lastValidatedAt: null,
    validationMessage: 'Awaiting DNS configuration',
    primary: false,
    forceHttps: false,
    requiredRecord: { type: 'CNAME', name: 'edge-stg', value: 'edge.deploycore.io' },
    detectedRecord: null,
    redirectRules: [],
  },
  {
    id: 'dom-07',
    domain: 'preview.daya.io',
    applicationId: 'app-daya-web',
    application: 'daya-web',
    environment: 'Preview',
    routingPort: 3000,
    dnsVerified: false,
    https: false,
    certExpiry: '—',
    certExpiryDays: 0,
    status: 'deploying',
    tlsState: 'VERIFYING',
    certificateIssuer: null,
    certificateIssuedAt: null,
    nextRenewalAt: null,
    lastValidatedAt: '30s ago',
    validationMessage: 'Checking CNAME against edge.deploycore.io',
    primary: false,
    forceHttps: true,
    requiredRecord: { type: 'CNAME', name: 'preview', value: 'edge.deploycore.io' },
    detectedRecord: { type: 'CNAME', name: 'preview', value: 'old.edge.example.net' },
    redirectRules: [],
  },
  {
    id: 'dom-08',
    domain: 'billing.daya.io',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    environment: 'Production',
    routingPort: 8080,
    dnsVerified: true,
    https: false,
    certExpiry: '—',
    certExpiryDays: 0,
    status: 'deploying',
    tlsState: 'ISSUING',
    certificateIssuer: null,
    certificateIssuedAt: null,
    nextRenewalAt: null,
    lastValidatedAt: '12s ago',
    validationMessage: 'Requesting certificate from Let\'s Encrypt',
    primary: false,
    forceHttps: true,
    requiredRecord: { type: 'CNAME', name: 'billing', value: 'edge.deploycore.io' },
    detectedRecord: { type: 'CNAME', name: 'billing', value: 'edge.deploycore.io' },
    redirectRules: [],
  },
]

export const volumes: Volume[] = [
  {
    id: 'vol-01',
    name: 'daya-primary-data',
    server: 'oci-singapore-01',
    driver: 'local',
    attachedResource: 'daya-primary',
    mountPath: '/var/lib/postgresql/data',
    backupPolicy: 'Daily · 30 day retention',
    status: 'healthy',
    usedGb: 84,
    totalGb: 200,
    mounts: 1,
  },
  {
    id: 'vol-02',
    name: 'ledger-audit-store',
    server: 'aws-us-east-04',
    driver: 'ebs',
    attachedResource: 'ledger-api',
    mountPath: '/data/audit',
    backupPolicy: 'Hourly · 7 day retention',
    status: 'healthy',
    usedGb: 42,
    totalGb: 100,
    mounts: 1,
  },
  {
    id: 'vol-03',
    name: 'signal-timeseries-data',
    server: 'hetzner-hel1-01',
    driver: 'local',
    attachedResource: 'signal-timeseries',
    mountPath: '/var/lib/postgresql/data',
    backupPolicy: 'Daily · 14 day retention',
    status: 'healthy',
    usedGb: 152,
    totalGb: 250,
    mounts: 1,
  },
  {
    id: 'vol-04',
    name: 'tools-uploads',
    server: 'bare-metal-dc3',
    driver: 'local',
    attachedResource: 'tools-admin',
    mountPath: '/app/uploads',
    backupPolicy: 'Not configured',
    status: 'degraded',
    usedGb: 6,
    totalGb: 20,
    mounts: 1,
  },
]

export const networks: DockerNetwork[] = [
  {
    id: 'net-01',
    name: 'daya-platform-prod',
    driver: 'bridge',
    scope: 'local',
    project: 'Daya Platform',
    environment: 'Production',
    connectedServices: ['daya-api', 'daya-web', 'daya-worker', 'session-cache'],
  },
  {
    id: 'net-02',
    name: 'ledger-core-prod',
    driver: 'overlay',
    scope: 'swarm',
    project: 'Ledger Core',
    environment: 'Production',
    connectedServices: ['ledger-api', 'ledger-reconciler', 'ledger-primary'],
  },
  {
    id: 'net-03',
    name: 'signal-ingest-prod',
    driver: 'bridge',
    scope: 'local',
    project: 'Signal Ingest',
    environment: 'Production',
    connectedServices: ['signal-collector', 'signal-docs', 'signal-timeseries'],
  },
  {
    id: 'net-04',
    name: 'edge-gateway-prod',
    driver: 'overlay',
    scope: 'swarm',
    project: 'Edge Gateway',
    environment: 'Production',
    connectedServices: ['edge-router'],
  },
]

export const containers: Container[] = [
  { id: 'ctr-01', name: 'daya-api-7f9c1', applicationId: 'app-daya-api', application: 'daya-api', revision: '00049', server: 'oci-singapore-01', image: 'daya-api:8f3a2c1', cpu: 34, memory: 61, memoryLimitMb: 2048, restarts: 0, status: 'healthy' },
  { id: 'ctr-02', name: 'daya-api-7f9c2', applicationId: 'app-daya-api', application: 'daya-api', revision: '00049', server: 'oci-singapore-01', image: 'daya-api:8f3a2c1', cpu: 29, memory: 58, memoryLimitMb: 2048, restarts: 0, status: 'healthy' },
  { id: 'ctr-03', name: 'daya-api-7f9c3', applicationId: 'app-daya-api', application: 'daya-api', revision: '00049', server: 'oci-singapore-01', image: 'daya-api:8f3a2c1', cpu: 38, memory: 64, memoryLimitMb: 2048, restarts: 1, status: 'healthy' },
  { id: 'ctr-04', name: 'daya-web-3a1c1', applicationId: 'app-daya-web', application: 'daya-web', revision: '00112', server: 'hetzner-fsn1-02', image: 'daya-web:a91cd44', cpu: 22, memory: 44, memoryLimitMb: 1024, restarts: 0, status: 'healthy' },
  { id: 'ctr-05', name: 'daya-web-3a1c2', applicationId: 'app-daya-web', application: 'daya-web', revision: '00111', server: 'hetzner-fsn1-02', image: 'daya-web:5cc9a02', cpu: 18, memory: 39, memoryLimitMb: 1024, restarts: 0, status: 'healthy' },
  { id: 'ctr-06', name: 'daya-worker-9e0b1', applicationId: 'app-daya-worker', application: 'daya-worker', revision: '00031', server: 'oci-singapore-01', image: 'daya-worker:c7e10bb', cpu: 58, memory: 39, memoryLimitMb: 1024, restarts: 0, status: 'deploying' },
  { id: 'ctr-07', name: 'ledger-api-4d81', applicationId: 'app-ledger-api', application: 'ledger-api', revision: '00204', server: 'aws-us-east-04', image: 'ledger-api:4dd88e2', cpu: 91, memory: 94, memoryLimitMb: 4096, restarts: 3, status: 'degraded' },
  { id: 'ctr-08', name: 'ledger-api-4d82', applicationId: 'app-ledger-api', application: 'ledger-api', revision: '00204', server: 'aws-us-east-04', image: 'ledger-api:4dd88e2', cpu: 85, memory: 90, memoryLimitMb: 4096, restarts: 2, status: 'degraded' },
  { id: 'ctr-09', name: 'edge-router-77a0', applicationId: 'app-edge-router', application: 'edge-router', revision: '00019', server: 'oci-frankfurt-02', image: 'edge-router:77a0cde', cpu: 0, memory: 0, memoryLimitMb: 512, restarts: 6, status: 'failed' },
  { id: 'ctr-10', name: 'signal-collector-d502', applicationId: 'app-signal-collector', application: 'signal-collector', revision: '00087', server: 'hetzner-hel1-01', image: 'signal-collector:d502f13', cpu: 19, memory: 31, memoryLimitMb: 512, restarts: 0, status: 'healthy' },
]

export const containerImages: ContainerImage[] = [
  { id: 'img-01', name: 'daya-api', tag: '8f3a2c1', digest: 'sha256:9d2c4a1e7f0b3c88…', application: 'daya-api', sizeMb: 184, createdAt: '12 min ago', location: 'registry.deploycore.io' },
  { id: 'img-02', name: 'daya-api', tag: '1a9e0dd', digest: 'sha256:7b1a3c9d5e2f0a44…', application: 'daya-api', sizeMb: 182, createdAt: '1 day ago', location: 'registry.deploycore.io' },
  { id: 'img-03', name: 'daya-web', tag: 'a91cd44', digest: 'sha256:c6b4d2e0f8a7c5b3…', application: 'daya-web', sizeMb: 96, createdAt: '38 min ago', location: 'registry.deploycore.io' },
  { id: 'img-04', name: 'daya-worker', tag: 'c7e10bb', digest: 'sha256:5e2f0a44c8b6d1e9…', application: 'daya-worker', sizeMb: 141, createdAt: '46s ago', location: 'registry.deploycore.io' },
  { id: 'img-05', name: 'ledger-api', tag: '4dd88e2', digest: 'sha256:1e9f2a4c6b4d2e0f…', application: 'ledger-api', sizeMb: 203, createdAt: '2 hr ago', location: 'ghcr.io/ledger' },
  { id: 'img-06', name: 'edge-router', tag: '77a0cde', digest: 'sha256:2e8f1a9c6b4d2e0f…', application: 'edge-router', sizeMb: 68, createdAt: '19 min ago', location: 'registry.deploycore.io' },
  { id: 'img-07', name: 'signal-collector', tag: 'd502f13', digest: 'sha256:f8a7c5b3d1e9f2a4…', application: 'signal-collector', sizeMb: 112, createdAt: '1 day ago', location: '123456.dkr.ecr.us-east-1.amazonaws.com' },
]

export const registries: Registry[] = [
  { id: 'reg-01', type: 'GitHub Container Registry', name: 'ghcr.io/daya', url: 'ghcr.io/daya', status: 'healthy', connectedAt: '8 mo ago', imageCount: 22 },
  { id: 'reg-02', type: 'Docker Hub', name: 'daya-platform', url: 'docker.io/daya-platform', status: 'healthy', connectedAt: '1 yr ago', imageCount: 9 },
  { id: 'reg-03', type: 'AWS ECR', name: 'signal-ecr', url: '123456.dkr.ecr.us-east-1.amazonaws.com', status: 'healthy', connectedAt: '4 mo ago', imageCount: 14 },
  { id: 'reg-04', type: 'GCP Artifact Registry', name: 'not connected', url: '—', status: 'unknown', connectedAt: '—', imageCount: 0 },
  { id: 'reg-05', type: 'Azure Container Registry', name: 'not connected', url: '—', status: 'unknown', connectedAt: '—', imageCount: 0 },
  { id: 'reg-06', type: 'Generic OCI Registry', name: 'registry.deploycore.io', url: 'registry.deploycore.io', status: 'healthy', connectedAt: '2 yr ago', imageCount: 58 },
]

export const gitProviders: GitProviderConnection[] = [
  { id: 'git-01', type: 'GitHub', account: 'daya-platform', organizations: ['daya', 'platform'], repositoryCount: 34, status: 'healthy', permissions: ['Read', 'Write', 'Webhooks', 'Deployments'], lastSync: '3 min ago' },
  { id: 'git-02', type: 'GitLab', account: 'not connected', organizations: [], repositoryCount: 0, status: 'unknown', permissions: [], lastSync: '—' },
  { id: 'git-03', type: 'Bitbucket', account: 'not connected', organizations: [], repositoryCount: 0, status: 'unknown', permissions: [], lastSync: '—' },
  { id: 'git-04', type: 'Generic Git', account: 'ledger-mirror', organizations: ['ledger'], repositoryCount: 4, status: 'healthy', permissions: ['Read'], lastSync: '1 hr ago' },
]

export const envVarHierarchy: EnvVarEntry[] = [
  { id: 'ev-01', key: 'LOG_LEVEL', value: 'info', secret: false, scope: 'Organization', source: 'DeployCore Org', overridden: false },
  { id: 'ev-02', key: 'NODE_ENV', value: 'production', secret: false, scope: 'Project', source: 'Daya Platform', overridden: false },
  { id: 'ev-03', key: 'DATABASE_URL', value: '••••••••••••', secret: true, scope: 'Project', source: 'Daya Platform', overridden: false },
  { id: 'ev-04', key: 'LOG_LEVEL', value: 'debug', secret: false, scope: 'Environment', source: 'Production', overridden: true },
  { id: 'ev-05', key: 'API_BASE_URL', value: 'https://api.daya.io', secret: false, scope: 'Environment', source: 'Production', overridden: false },
  { id: 'ev-06', key: 'STRIPE_SECRET_KEY', value: '••••••••••••', secret: true, scope: 'Application', source: 'daya-api', overridden: false },
  { id: 'ev-07', key: 'PORT', value: '8080', secret: false, scope: 'Application', source: 'daya-api', overridden: true },
  { id: 'ev-08', key: 'QUEUE_CONCURRENCY', value: '12', secret: false, scope: 'Application', source: 'daya-api', overridden: false },
]

export const healthChecks: HealthCheckConfig[] = [
  {
    id: 'hc-01',
    applicationId: 'app-daya-api',
    application: 'daya-api',
    type: 'HTTP',
    path: '/healthz',
    port: 8080,
    interval: 30,
    timeout: 5,
    retries: 3,
    initialDelay: 10,
    expectedStatus: 200,
    status: 'healthy',
    history: Array.from({ length: 12 }).map((_, i) => ({ timestamp: `${(12 - i) * 30}s ago`, status: 'pass' as const, latencyMs: 22 + (i % 4) * 3 })),
  },
  {
    id: 'hc-02',
    applicationId: 'app-ledger-api',
    application: 'ledger-api',
    type: 'HTTP',
    path: '/health',
    port: 4000,
    interval: 15,
    timeout: 3,
    retries: 2,
    initialDelay: 15,
    expectedStatus: 200,
    status: 'degraded',
    history: Array.from({ length: 12 }).map((_, i) => ({ timestamp: `${(12 - i) * 15}s ago`, status: i % 5 === 0 ? ('fail' as const) : ('pass' as const), latencyMs: 180 + (i % 3) * 40 })),
  },
  {
    id: 'hc-03',
    applicationId: 'app-edge-router',
    application: 'edge-router',
    type: 'TCP',
    path: '—',
    port: 443,
    interval: 10,
    timeout: 2,
    retries: 3,
    initialDelay: 5,
    expectedStatus: 0,
    status: 'failed',
    history: Array.from({ length: 12 }).map((_, i) => ({ timestamp: `${(12 - i) * 10}s ago`, status: 'fail' as const, latencyMs: 0 })),
  },
  {
    id: 'hc-04',
    applicationId: 'app-signal-collector',
    application: 'signal-collector',
    type: 'Command',
    path: 'pgrep -f collector',
    port: 0,
    interval: 60,
    timeout: 5,
    retries: 3,
    initialDelay: 20,
    expectedStatus: 0,
    status: 'healthy',
    history: Array.from({ length: 12 }).map((_, i) => ({ timestamp: `${(12 - i) * 60}s ago`, status: 'pass' as const, latencyMs: 4 + (i % 2) })),
  },
]

export const backupJobs: BackupJob[] = [
  {
    id: 'bkj-01',
    database: 'daya-primary',
    databaseId: 'db-01',
    policy: 'Daily at 02:00 UTC',
    destination: 'S3 · deploycore-backups-sg',
    lastSuccess: '38 min ago',
    nextRun: 'in 23h 22m',
    retention: '30 days',
    status: 'healthy',
  },
  {
    id: 'bkj-02',
    database: 'ledger-primary',
    databaseId: 'db-02',
    policy: 'Every 6 hours',
    destination: 'S3 · deploycore-backups-us',
    lastSuccess: '2 hr ago',
    nextRun: 'in 4h',
    retention: '90 days',
    status: 'healthy',
  },
  {
    id: 'bkj-03',
    database: 'signal-timeseries',
    databaseId: 'db-03',
    policy: 'Daily at 03:30 UTC',
    destination: 'S3 · deploycore-backups-eu',
    lastSuccess: '12 min ago',
    nextRun: 'in 23h 18m',
    retention: '14 days',
    status: 'healthy',
  },
  {
    id: 'bkj-04',
    database: 'tools-metadata',
    databaseId: 'db-05',
    policy: 'Weekly on Sunday',
    destination: 'S3 · deploycore-backups-dc3',
    lastSuccess: '5 hr ago',
    nextRun: 'in 6d 19h',
    retention: '60 days',
    status: 'degraded',
  },
  {
    id: 'bkj-05',
    database: 'session-cache',
    databaseId: 'db-04',
    policy: 'Not configured',
    destination: '—',
    lastSuccess: 'never',
    nextRun: '—',
    retention: '—',
    status: 'unknown',
  },
]

export const backupRuns: BackupRun[] = [
  {
    id: 'bkr-01',
    backupJobId: 'bkj-01',
    database: 'daya-primary',
    databaseId: 'db-01',
    status: 'success',
    startedAt: '2026-09-14 09:00:00',
    completedAt: '2026-09-14 09:00:48',
    duration: '48s',
    sizeGb: 6.2,
    destination: 'S3 · deploycore-backups-sg',
    checksum: 'sha256:a1b2c3d4e5f60718',
  },
  {
    id: 'bkr-02',
    backupJobId: 'bkj-01',
    database: 'daya-primary',
    databaseId: 'db-01',
    status: 'success',
    startedAt: '2026-09-13 09:00:00',
    completedAt: '2026-09-13 09:00:51',
    duration: '51s',
    sizeGb: 6.1,
    destination: 'S3 · deploycore-backups-sg',
    checksum: 'sha256:e5f6a7b8c9d0e1f2',
  },
  {
    id: 'bkr-03',
    backupJobId: 'bkj-01',
    database: 'daya-primary',
    databaseId: 'db-01',
    status: 'success',
    startedAt: '2026-09-12 09:00:00',
    completedAt: '2026-09-12 09:00:44',
    duration: '44s',
    sizeGb: 6.0,
    destination: 'S3 · deploycore-backups-sg',
    checksum: 'sha256:c9d0e1f23a4b5c6d',
  },
  {
    id: 'bkr-04',
    backupJobId: 'bkj-02',
    database: 'ledger-primary',
    databaseId: 'db-02',
    status: 'running',
    startedAt: '2026-09-14 14:00:00',
    completedAt: '—',
    duration: '12m…',
    sizeGb: 0,
    destination: 'S3 · deploycore-backups-us',
    checksum: '—',
  },
  {
    id: 'bkr-05',
    backupJobId: 'bkj-02',
    database: 'ledger-primary',
    databaseId: 'db-02',
    status: 'success',
    startedAt: '2026-09-14 08:00:00',
    completedAt: '2026-09-14 08:04:12',
    duration: '4m 12s',
    sizeGb: 28.4,
    destination: 'S3 · deploycore-backups-us',
    checksum: 'sha256:1122334455667788',
  },
  {
    id: 'bkr-06',
    backupJobId: 'bkj-03',
    database: 'signal-timeseries',
    databaseId: 'db-03',
    status: 'success',
    startedAt: '2026-09-14 03:30:00',
    completedAt: '2026-09-14 03:32:08',
    duration: '2m 8s',
    sizeGb: 14.1,
    destination: 'S3 · deploycore-backups-eu',
    checksum: 'sha256:99aabbccddeeff00',
  },
  {
    id: 'bkr-07',
    backupJobId: 'bkj-04',
    database: 'tools-metadata',
    databaseId: 'db-05',
    status: 'failed',
    startedAt: '2026-09-08 00:00:00',
    completedAt: '2026-09-08 00:00:12',
    duration: '12s',
    sizeGb: 0.4,
    destination: 'S3 · deploycore-backups-dc3',
    checksum: 'sha256:3a4b5c6d7e8f9012',
  },
  {
    id: 'bkr-08',
    backupJobId: 'bkj-04',
    database: 'tools-metadata',
    databaseId: 'db-05',
    status: 'success',
    startedAt: '2026-09-01 00:00:00',
    completedAt: '2026-09-01 00:00:15',
    duration: '15s',
    sizeGb: 0.4,
    destination: 'S3 · deploycore-backups-dc3',
    checksum: 'sha256:7e8f9a0b1c2d3e4f',
  },
]

export const notificationChannels: NotificationChannel[] = [
  { id: 'nc-01', type: 'Email', name: 'Platform Team', target: 'platform@daya.io', status: 'healthy' },
  { id: 'nc-02', type: 'Slack', name: '#deploys', target: 'daya-workspace', status: 'healthy' },
  { id: 'nc-03', type: 'Microsoft Teams', name: 'Ops Channel', target: 'not connected', status: 'unknown' },
  { id: 'nc-04', type: 'Discord', name: 'not connected', target: '—', status: 'unknown' },
  { id: 'nc-05', type: 'Telegram', name: 'Incident Bot', target: '@deploycore_alerts', status: 'healthy' },
  { id: 'nc-06', type: 'Webhook', name: 'PagerDuty Ingest', target: 'https://events.pagerduty.com/…', status: 'healthy' },
  { id: 'nc-07', type: 'WhatsApp', name: 'not connected', target: '—', status: 'unknown' },
]

export const notificationPolicies: NotificationPolicy[] = [
  { id: 'np-01', name: 'Production deployment failures', when: 'Deployment Failed', conditions: ['Environment = Production'], channels: ['Email', 'Slack'], enabled: true },
  { id: 'np-02', name: 'Certificate expiry warning', when: 'Certificate Expiring', conditions: ['Days remaining <= 14'], channels: ['Slack'], enabled: true },
  { id: 'np-03', name: 'Server offline', when: 'Server Health Changed', conditions: ['Status = Offline'], channels: ['Email', 'Telegram', 'Webhook'], enabled: true },
  { id: 'np-04', name: 'Backup failure', when: 'Backup Failed', conditions: ['Any environment'], channels: ['Email'], enabled: false },
]

export const webhooks: Webhook[] = [
  {
    id: 'wh-01',
    name: 'CI Deploy hooks',
    endpoint: 'https://ci.daya.io/hooks/deploycore',
    events: ['deployment.started', 'deployment.succeeded', 'deployment.failed'],
    enabled: true,
    status: 'healthy',
    latestDelivery: '12 min ago',
    signingSecretMasked: 'whsec_••••••••7f2a',
    deliveries: [
      {
        id: 'whd-01',
        timestamp: '12 min ago',
        statusCode: 200,
        latencyMs: 142,
        request: '{"event":"deployment.succeeded","id":"dep-293"}',
        response: '{"ok":true}',
        retried: false,
        attempts: 1,
      },
      {
        id: 'whd-02',
        timestamp: '46s ago',
        statusCode: 200,
        latencyMs: 98,
        request: '{"event":"deployment.started","id":"dep-292"}',
        response: '{"ok":true}',
        retried: false,
        attempts: 1,
      },
      {
        id: 'whd-03',
        timestamp: '19 min ago',
        statusCode: 502,
        latencyMs: 5012,
        request: '{"event":"deployment.failed","id":"dep-291"}',
        response: '{"error":"upstream timeout"}',
        retried: true,
        attempts: 3,
      },
    ],
  },
  {
    id: 'wh-02',
    name: 'Ops Slack relay',
    endpoint: 'https://hooks.slack.com/services/T000/B000/XXXX',
    events: ['server.offline', 'certificate.expiring'],
    enabled: true,
    status: 'healthy',
    latestDelivery: '18 min ago',
    signingSecretMasked: 'whsec_••••••••a913',
    deliveries: [
      {
        id: 'whd-04',
        timestamp: '18 min ago',
        statusCode: 200,
        latencyMs: 210,
        request: '{"event":"certificate.expiring","domain":"edge.daya.io"}',
        response: 'ok',
        retried: false,
        attempts: 1,
      },
    ],
  },
  {
    id: 'wh-03',
    name: 'Backup notifier',
    endpoint: 'https://ops.ledger.io/webhooks/backups',
    events: ['backup.completed', 'backup.failed'],
    enabled: false,
    status: 'stopped',
    latestDelivery: '5 day ago',
    signingSecretMasked: 'whsec_••••••••c401',
    deliveries: [
      {
        id: 'whd-05',
        timestamp: '5 day ago',
        statusCode: 429,
        latencyMs: 88,
        request: '{"event":"backup.failed","database":"tools-metadata"}',
        response: '{"error":"rate_limited"}',
        retried: true,
        attempts: 4,
      },
    ],
  },
]

export const teamMembers: TeamMember[] = [
  { id: 'usr-01', name: 'Amara Osei', email: 'amara@daya.io', role: 'Owner', teams: ['Platform'], status: 'healthy', lastActive: '2 min ago' },
  { id: 'usr-02', name: 'Marcus Lindqvist', email: 'marcus@daya.io', role: 'Administrator', teams: ['Ledger'], status: 'healthy', lastActive: '38 min ago' },
  { id: 'usr-03', name: 'Priya Chandran', email: 'priya@daya.io', role: 'DevOps', teams: ['Signal', 'Platform'], status: 'healthy', lastActive: '19 min ago' },
  { id: 'usr-04', name: 'Jonas Weber', email: 'jonas@daya.io', role: 'Developer', teams: ['Internal Tools'], status: 'healthy', lastActive: '1 hr ago' },
  { id: 'usr-05', name: 'Sofia Reyes', email: 'sofia@daya.io', role: 'Developer', teams: ['Ledger'], status: 'healthy', lastActive: '3 hr ago' },
  { id: 'usr-06', name: 'Tobias Mensah', email: 'tobias@daya.io', role: 'Support', teams: ['Platform'], status: 'degraded', lastActive: '2 day ago' },
  { id: 'usr-07', name: 'Nadia Farouk', email: 'nadia@daya.io', role: 'Viewer', teams: ['Signal'], status: 'healthy', lastActive: '5 day ago' },
]

export const teams: Team[] = [
  { id: 'team-01', name: 'Platform', memberCount: 3, members: ['Amara Osei', 'Priya Chandran', 'Tobias Mensah'] },
  { id: 'team-02', name: 'Ledger', memberCount: 2, members: ['Marcus Lindqvist', 'Sofia Reyes'] },
  { id: 'team-03', name: 'Signal', memberCount: 2, members: ['Priya Chandran', 'Nadia Farouk'] },
  { id: 'team-04', name: 'Internal Tools', memberCount: 1, members: ['Jonas Weber'] },
]


export const invitations: Invitation[] = [
  {
    id: 'inv-01',
    email: 'lena@daya.io',
    role: 'Developer',
    teams: ['Platform'],
    invitedBy: 'amara@daya.io',
    invitedAt: '2 day ago',
    expiresAt: 'in 5 days',
    status: 'pending',
  },
  {
    id: 'inv-02',
    email: 'kai@signal.io',
    role: 'Viewer',
    teams: ['Signal'],
    invitedBy: 'priya@daya.io',
    invitedAt: '6 day ago',
    expiresAt: 'in 1 day',
    status: 'pending',
  },
  {
    id: 'inv-03',
    email: 'ops@ledger.io',
    role: 'DevOps',
    teams: ['Ledger'],
    invitedBy: 'marcus@daya.io',
    invitedAt: '12 day ago',
    expiresAt: 'expired 2 days ago',
    status: 'expired',
  },
  {
    id: 'inv-04',
    email: 'maya@daya.io',
    role: 'Support',
    teams: ['Platform'],
    invitedBy: 'amara@daya.io',
    invitedAt: '3 week ago',
    expiresAt: 'accepted',
    status: 'accepted',
  },
]

export const roleNames = ['Owner', 'Administrator', 'DevOps', 'Developer', 'Support', 'Viewer'] as const

export const permissionResources = ['Servers', 'Applications', 'Deployments', 'Databases', 'Secrets', 'Domains', 'Backups', 'Organization'] as const

export type { PermissionLevel } from '@/lib/types'

export const permissionMatrix: Record<string, Record<string, PermissionLevel>> = {
  Owner: { Servers: 'full', Applications: 'full', Deployments: 'full', Databases: 'full', Secrets: 'full', Domains: 'full', Backups: 'full', Organization: 'full' },
  Administrator: { Servers: 'full', Applications: 'full', Deployments: 'full', Databases: 'full', Secrets: 'full', Domains: 'full', Backups: 'full', Organization: 'edit' },
  DevOps: { Servers: 'edit', Applications: 'edit', Deployments: 'full', Databases: 'edit', Secrets: 'edit', Domains: 'edit', Backups: 'edit', Organization: 'view' },
  Developer: { Servers: 'view', Applications: 'edit', Deployments: 'edit', Databases: 'view', Secrets: 'view', Domains: 'view', Backups: 'none', Organization: 'none' },
  Support: { Servers: 'view', Applications: 'view', Deployments: 'view', Databases: 'view', Secrets: 'none', Domains: 'view', Backups: 'none', Organization: 'none' },
  Viewer: { Servers: 'view', Applications: 'view', Deployments: 'view', Databases: 'view', Secrets: 'none', Domains: 'view', Backups: 'none', Organization: 'none' },
}

export const organizations: Organization[] = [
  { id: 'org-01', name: 'Daya Inc.', plan: 'Enterprise', userCount: 34, serverCount: 22, status: 'healthy', createdAt: '2 yr ago' },
  { id: 'org-02', name: 'Ledger Core Systems', plan: 'Business', userCount: 12, serverCount: 8, status: 'healthy', createdAt: '1 yr ago' },
  { id: 'org-03', name: 'Signal Labs', plan: 'Team', userCount: 6, serverCount: 4, status: 'healthy', createdAt: '8 mo ago' },
  { id: 'org-04', name: 'Sandbox Trial Co.', plan: 'Trial', userCount: 2, serverCount: 1, status: 'degraded', createdAt: '4 day ago' },
]

export const platformJobs: PlatformJob[] = [
  { id: 'pj-01', name: 'certificate-renewal-sweep', type: 'Scheduled', status: 'healthy', startedAt: '10 min ago', duration: '4s' },
  { id: 'pj-02', name: 'usage-billing-rollup', type: 'Scheduled', status: 'healthy', startedAt: '1 hr ago', duration: '22s' },
  { id: 'pj-03', name: 'orphaned-volume-gc', type: 'Scheduled', status: 'degraded', startedAt: '3 hr ago', duration: '1m 12s' },
  { id: 'pj-04', name: 'agent-fleet-healthcheck', type: 'Recurring', status: 'healthy', startedAt: '4s ago', duration: '1s' },
  { id: 'pj-05', name: 'org-sandbox-trial-004-provision', type: 'One-off', status: 'failed', startedAt: '4 day ago', duration: '8s' },
]

export const featureFlags: FeatureFlag[] = [
  { id: 'ff-01', name: 'Revision traffic splitting', key: 'revisions.traffic-split', enabled: true, rollout: 100, environment: 'All' },
  { id: 'ff-02', name: 'Zero-downtime volume migration', key: 'volumes.live-migrate', enabled: true, rollout: 25, environment: 'Production' },
  { id: 'ff-03', name: 'AI deployment risk score', key: 'deployments.risk-score', enabled: false, rollout: 0, environment: 'All' },
  { id: 'ff-04', name: 'Multi-region failover', key: 'servers.multi-region-failover', enabled: true, rollout: 100, environment: 'All' },
  { id: 'ff-05', name: 'New billing dashboard', key: 'billing.new-dashboard', enabled: true, rollout: 60, environment: 'All' },
]

export const platformVersions = [
  { component: 'Control Plane', version: 'v4.12.0', status: 'healthy' as const, updatedAt: '3 day ago' },
  { component: 'Node Agent', version: 'v2.4.1', status: 'healthy' as const, updatedAt: '9 day ago' },
  { component: 'Registry Proxy', version: 'v1.8.3', status: 'healthy' as const, updatedAt: '21 day ago' },
  { component: 'Edge Router', version: 'v3.1.0', status: 'degraded' as const, updatedAt: '2 day ago' },
]

export function generateLogLines(container: string, count = 60): LogLine[] {
  const levels: LogLine['level'][] = ['info', 'info', 'info', 'debug', 'warn', 'info', 'error', 'info']
  const messages = [
    'Handled GET /v1/accounts/442198 in 42ms',
    'Connection pool utilization at 61%',
    'Health check passed',
    'Received SIGTERM, draining connections',
    'Cache miss for key session:8f21a',
    'Retrying upstream request (attempt 2/3)',
    'Rate limit threshold reached for client 10.0.4.12',
    'Queued job process_payout#88213',
    'Completed job process_payout#88213 in 118ms',
    'Slow query detected: 812ms — SELECT * FROM ledger_entries',
    'Failed to reach upstream host registry.deploycore.io',
    'Container memory usage at 512MB / 1024MB',
    'Rotating log file deploycore.log',
    'New connection from 10.0.1.22:54012',
  ]
  // Fixed anchor timestamp (rather than Date.now()) keeps output deterministic
  // between server and client renders, avoiding hydration mismatches.
  const anchor = new Date('2026-09-14T10:15:00Z').getTime()
  return Array.from({ length: count }).map((_, i) => ({
    id: `log-${container}-${i}`,
    timestamp: new Date(anchor - (count - i) * 4000).toISOString().slice(11, 19),
    level: levels[i % levels.length],
    container,
    message: messages[i % messages.length],
  }))
}
