/** @deprecated Import from `@/components/platform` instead. */
export { PageHeader } from '@/components/platform/page-header'
export { EmptyState } from '@/components/platform/empty-state'
export { StatusBadge } from '@/components/platform/status-badge'
export { HealthIndicator } from '@/components/platform/health-indicator'
export { EnvironmentBadge } from '@/components/platform/environment-badge'
export { Metric } from '@/components/platform/metric'
export { MetricCard } from '@/components/platform/metric-card'
export { ResourceUsageBar } from '@/components/platform/resource-usage-bar'
export { ConfirmDialog } from '@/components/platform/confirm-dialog'
export { CommandPalette } from '@/components/platform/command-palette'
export { CopyButton } from '@/components/platform/copy-button'
export { CodeBlock } from '@/components/platform/code-block'
export { SecretField } from '@/components/platform/secret-field'
export { LogViewer } from '@/components/platform/log-viewer'
export { DeploymentPipeline } from '@/components/platform/deployment-pipeline'
export { ActivityFeed, ActivityTimeline } from '@/components/platform/activity-timeline'
export { AppSidebar } from '@/components/platform/app-sidebar'
export { TopBar as AppHeader } from '@/components/platform/top-bar'
